### ISSUE TITLE
[v6] casual key issue pod C3084696

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#101]
Submitter: dragonc0
Email: dragonc0@hotmail.com
[v6] C3084696

In palace of darkness there are two keys in the dark with lamp behind a key door:

[dungeon-D1-1F] Dark Palace - big key room................................................Lamp
[dungeon-D1-1F] Dark Palace - maze room [top chest].......................................Key
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [left chest]......................Key

If you open the maze door without the lamp you might not have enough keys left to get to the lamp (leaves the keydoor to the lamp and to the boss in the dark closed). As speedrunners it isn't an issue since we know there is darkness in the maze. Casuals however (or people who forgot they don't have lamp) can make this mistake which would force them to find a key in the dark.

I don't know if this is major enough to require a fix just to prevent a casual semi-keylock

**Comment by ChristosOwen** [comment]
The only sure way of ensuring this never happens is to make sure there's only ever 1 small key in any of the 4 dark chests (2 in dark maze and 2 in basement) if Lamp is behind a locked door in PoD (spike statue room or big key room). 

If there is more than one small key in these chests you could always have situations where you'd be a key short and navigating in the dark would be required.

Dessy - this should be easily fixed with functions. This, together with the bow/hammer/key logic from the other bug report, means PoD is going to have to be redone quite heavily. Let me know if you need any help with it.

**Comment by ChristosOwen** [comment]
Actually a better solution is simply:

If there is more than 1 small key in the 4 dark chests (2 basement, 2 dark maze), then lamp cannot be in spike statue room or big key room. This should be easy with functions.

**Comment by ChristosOwen** [comment]
Closing as summarised all of PoD in one report; #123
