### ISSUE TITLE
Suggestion: Incentives for pulling Master Sword?

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#108]
Submitter: Marx
What if pulling the Master Sword in the Lost Woods sets a flag that gives you the slightly longer length Sword levels 2, 3, and 4 normally have, as well as the sword beams at full health and the ability to activate the Ether and Bombos Tablets (assuming you have Book of Mudora)?
It seems rather common that you are able to skip pulling the Master Sword since getting Titan's Mitts, Tempered Sword, etc, makes pulling the sword pointless, so I thought maybe there should be some incentive to go through the trouble of getting it. On that note, there's already a reason to get Pendant of Courage since Sahasralah might have something good.
You would still be able to upgrade the Fighter's Sword to Tempered or better, but unless you pull the Master Sword it wouldn't be able to fire sword beams and it would still have the same length/range as the Fighter's Sword. As for the tablets, their inscriptions do say "Hold up the Master Sword and you will get the magic of...", so it would make sense for the tablets to actually require that.
As a bonus, maybe you can make the Master Sword credits text dynamic like you did with King Zora's part, where if you never pull the sword, it would just say "And the Master Sword sleeps... Forever!" (dropping the "again" in the text)

**Comment by ChristosOwen** [comment]
Interesting idea. The current idea is to randomize the Master, Tempered and Gold swords between the Lost Woods pedastal, smith's house and fat faerie. So you'll always get one of those swords from one of those locations. This means for the Lost Woods pedastal the incentive would be you'd now have a chance of it being an even better sword (Tempered/Gold).

This also means we'd be more likely to see people getting either the Lost Woods pedastal or fat faerie swords if the smiths only give you the Master Sword!

What do you think of this current idea?

I'm not sure players would like the swords behaviour to be changed - players are very used to the length of the swords and it would become very noticable in gameplay if it was shorter - the Blind fight comes to mind, which is somewhat different with the shorter fighter's sword. Generally players would notice things not working that normally would work due to the shorter sword, most of it they'd do unconciously without thinking, so it would be frustrating. 

Lack of swordbeams would probably be less troublesome but people do use them for some strategies, so removing them would probably be recieved negatively as well. This is just my opinion of course!

**Comment by BlueViper85** [comment]
Just to toss in my 2 cents here, I do like the idea of randomizing the swords among themselves, but not the length. As Chris said, the length of the sword and the beams would seem like a bit too much.  When you have a certain sword you expect to be able to do certain things with it, and I don't think randomizing the lengths/beams adds anything too meaningful in the end.

**Comment by KatDevsGames** [comment]
Randomizing the swords themselves would be cool. Imagine pulling the tempered sword from the master sword pedestal or getting gold sword from the dwarves, etc.

**Comment by ChristosOwen** [comment]
Agreed... this is in the doc! I'd personally vote for this to be prioritized above shops/faerie fountains ;)

Closing this now too as we've reached a concensus.
