### ISSUE TITLE
[v6] - Graphical glitch with 1/4 magic

### ISSUE THREAD

**Issue by Omio** [Dessyreqt/alttprandomizer#113]
[Screenshot here showing the gfx glitching out by the Magic Meter.](http://puu.sh/qNZgy/460687a236.png)

Screenshot+headline should describe everything.

EDIT: The seed used, if relevant, is 1337

**Comment by BlueViper85** [comment]
To add some detail here, this glitch is tied specifically to the Game Over screen.  As soon as the G in "Game over" starts to slide in the 1/4 text changes to what's shown in the screenshot.  It remains in this state until you select "Save and Continue" (the top option on the GO screen).

For video of this in action, check out this VoD https://www.twitch.tv/darkmagician1184/v/85575930?t=04m52s

Side note: the video was from a customized seed as opposed to a randomizer-generated seed.  However, this post suggests that this issue is agnostic of the method of ROM generation.

**Comment by KatDevsGames** [comment]
Smallhacker figured out why this happens. I know how to fix it. Leaving this open until I actually do the patch.

**Comment by ChristosOwen** [comment]
This had been addressed and will be working correctly in v7.
