### ISSUE TITLE
[v6] Blue Chest won't travel to Light World

### ISSUE THREAD

**Issue by Rankshot** [Dessyreqt/alttprandomizer#115]
Hello, I am currently having an issue with the Blue Chest that appears after getting the Tempered Sword.  I go to pick it up as normal and immediately warp to the Light World with it, but when I do the blue chest disappears and goes back to its original spot in the Dark World, and I've done this three times; once right outside the smithy, once near the Haunted Grove, and once near the guy you take it to, and it still doesn't warp with me like it's supposed to.  Is this a bug, and if so can it be fixed?

**Comment by BlueViper85** [comment]
The Blue/Purple Chest is known as a "follower" which are removed under certain circumstances.  This could potentially be triggered incorrectly.

Four questions for you:
1. Do you have video of this happening?
2. Have you been using the mirror to warp from Dark World to light world?
3. What seed are you playing?
4.  Have you visited any fairy fountains?

**Comment by Rankshot** [comment]
I don't have a video, yes I have been using the mirror to warp from Dark World to the Light World, the seed I am playing is C7521285 and I have visited a few Fairy Fountains, the one between Lake Hylia and Eastern Palace, and the one you open up on Death Mountain when going to the floating island.

Could it have anything to do with me not killing Agahnim yet?  Because I remember killing Agahnim on a previous seed, C3071473, and the same thing happened when I went to do the Blue Chest.

**Comment by BlueViper85** [comment]
Thanks for the additional info! This certainly shouldn't happen. I'll test some of this and see if I'm able to recreate the problem using potentially a combination of these seeds and others if necessary.

Some unusual behavior has been witnessed with the fairies, so that's why I inquired about that. I'll be sure to test those specifically to see if they might be related.

Can't necessarily rule anything out without looking and testing further. But given what you said and that so many other seeds have been played it seems unlikely that Agahnim being beaten or not would cause this.

**Comment by BlueViper85** [comment]
I've been playing around with this a little bit and haven't had much luck recreating it so far in other seeds.  I've generated C7521285 and am playing through that now.  Are you playing this on an emulator?  If so, some emulators generate an SRM or a .save file, can you see if you have one for either seed and if so could you upload it or send it to me? I can provide an e-mail if you need to send the file directly.

**Comment by Rankshot** [comment]
I am using snes9x 1.53 to run the rom, and I'll gladly upload to here directly.  This contains a copy of my current save file.
[ALttP Random - C7521285.zip](https://github.com/Dessyreqt/alttprandomizer/files/438659/ALttP.Random.-.C7521285.zip)

**Comment by BlueViper85** [comment]
I am also using Snes9x 1.53 and have been unable to recreate this using my own generated seed, one of the seed numbers you provided or even with your SRM file.

I've verified that it's not part of any of the layers and only disappears with all the sprites when they are disabled, so it's not likely a setting in SNES9x.

To be safe, could you also provide the SFC file the randomizer generated?

Just to confirm, if you were to load up the ROM now yourself would it still not work?  What happens if you pick up the chest and then save + quit and load back up? Does it stay with you that way or does it disappear when you reload the save too?

I can't keep testing tonight, but I'll pick this back up tomorrow when I can.

**Comment by Rankshot** [comment]
Alright I can do that, here is a copy of the exact sfc file I use.
[ALttP Random - C7521285.zip](https://github.com/Dessyreqt/alttprandomizer/files/438736/ALttP.Random.-.C7521285.zip)

**Comment by Rankshot** [comment]
So I started a new game with a fresh rom, C8453784, and I now got the Blue Chest to follow me into the Light World(Item inside being the Magic Powder), only thing I did different was I did this while the Master Sword was in the Smithy being worked on, only Fairy Fountains visited up to this point was the one you bomb open in the Dark World when getting to the floating island, the one near Misery Mire as a Pink Rabbit, and Venus, Queen of the Fairies for bomb sack upgrades.  No Dark World dungeons have been entered yet.

**Comment by BlueViper85** [comment]
I cannot recreate this with your SRM file or your SFC file.  I had several new idea pop in my head that I tried tonight, but none led to being able to recreate this issue.  This is the first it has come up, so my latest thinking is that maybe this could relate to having some or all of the pendants (and maybe a combination of that and visiting a great fairy?) since so few people tend to get al the pendants (explaining the rarity), but that has proven unsuccessful so far.

I also messed around with various combinations of saving and quitting and other game events (fairies, agahnim, master sword, all to no avail.  What ever caused this had to have been rather specific.

I'm glad to hear that it's working OK in the latest seed you played, though.

When you tried several different times, I assume that means that when you went back to the dark world after it failed to follow you it was back in its original location and you were able to go back and pick it up and mirror again (only to find it still didn't follow you to LW)?

**Comment by Rankshot** [comment]
Yes, several tries on two different seeds, only the latest seed allowed me to take the Blue Chest to the Light World.  Could all of this be a result of removing the "Invisible Follower" you get after getting the Master Sword, or could it be affected by later followers, like Disguised Blind, Kiki the Monkey and, I guess by technicality, the Super Bomb for some reason?

**Comment by KatDevsGames** [comment]
Alterations to attaching the invisible follower after the master sword would not affect this directly and, at any rate, would have presented itself almost immediately and in a widespread way rather than this isolated case.

On August 26, 2016 11:56:42 PM EDT, Rankshot notifications@github.com wrote:

> Yes, several tries on two different seeds, only the latest seed allowed
> me to take the Blue Chest to the Light World.  Could all of this be a
> result of removing the "Invisible Follower" you get after getting the
> Master Sword, or could it be affected by later followers, like
> Disguised Blind, Kiki the Monkey and, I guess by technicality, the
> Super Bomb for some reason?
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/115#issuecomment-242894011

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Rankshot** [comment]
Alright, that's good to know.

**Comment by ChristosOwen** [comment]
Nobody has been able to replicate this, so no fix is really possible since it hasn't happened again to anyone. We're addressing the purple chest in a slightly different issue report #124 anyway so we can monitor what happens there.
