### ISSUE TITLE
[v6] dungeon 6 softlock 

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#118]
Submitter: jdkl85
Email: jdkl85@gmail.com
[v6] seed:C1197308

2? keys behind locked door on left of main room caused me to be soft locked from completing dungeon 6.  I had to use a GameGenie code to open a locked door to proceed.

**Comment by BlueViper85** [comment]
Looking at the spoiler log, while there were keys after that door, the big key was accessible without going through that door allowing access to the Big Chest. Nothing else of value existed in the dungeon. Based on this, the seed appears solvable without requiring glitches or codes.

Responded via e-mail so they could see this as well.

**Comment by ChristosOwen** [comment]
Even beyond this, with the pot key in room with spikes which spawns a chest you have a choice of 3 doors you can open (the one above it, leading to a big room with spikes and another small key; one in the south of that big room with spikes; one on the left side of the main lobby) and regardless of which door you open you're able to hit a crystal switch. This then opens up the main lobby small chest and the map room small chest (near the Big Chest). Assuming you opened the 2 "useless" doors and not the west side door, you now have a key to open this door -- unless you open the small key door right next to map chest. If you do this then you can't go to the west side of Mire. However this can only ever happen if the west side of Mire contains 2 small keys in those chests, and since you don't need the small keys to complete the dungeon, it's not actually an issue. You also could have used the Big Key to go down to the basement and hit the crystal switch there without opening any small key doors (by going through the upper left door of main lobby).

Dessy -- this key generation does indeed allow you to block off the west side of Mire if you open all other doors. However this is only possible if both those chests are small keys, so by definition it never matters if you do actually do this. Up to you whether you want to do anything here or not -- if you want to prevent it, then simplest way is to use a function/keyzones to simply restrict the two west side chests so only one small key can spawn there.

**Comment by KatDevsGames** [comment]
Personally, I like the idea of dungeon sections sometimes being closed off by the randomization.

**Comment by BlueViper85** [comment]
Agreed, of course assuming nothing useful is on the other side.

**Comment by ChristosOwen** [comment]
This is now irrelevant due to the more recent realisation in report #130
