### ISSUE TITLE
[v6] Defeating Agahnim (Light World) disables mini-lamp.

### ISSUE THREAD

**Issue by TonyTheTGR** [Dessyreqt/alttprandomizer#120]
Once you beat Agahnim and you get warped to the Dark World, the little area-of-effect visibility that is toggled in by default becomes disabled if you don't have the lamp. This can make a few sequences _really_ difficult... though technically not impossible. But in case you want it fixed... I'd presume so.

**Comment by KatDevsGames** [comment]
This behavior is intentional. Please see release notes. The "free" lantern light is available only in the light world. You don't get free lantern in the dark world as it's the... dark... world.

Please be assured that no seeds will ever REQUIRE you to pass through dark rooms. The lantern is guaranteed to be available before any dark rooms are required to be completed to progress further.

**Comment by TonyTheTGR** [comment]
Fair enough.
