### ISSUE TITLE
Suggestion: Shuffle secondary underworld entrances

### ISSUE THREAD

**Issue by churine** [Dessyreqt/alttprandomizer#122]
The secondary underworld is basically all minor rooms, houses, caves, shops, ponds etc that are standalone single entrance-exit, and obviously not dungeons nor complex cave systems or need to connect entrances. Some are even repeated to act as different instances of the rooms they point.

Since these generally contain a few heart pieces and specific items among a lot of usually never-visited rooms, it could be interesting to have these in new locations, and not that far from the spirit of the randomizer I'd think.

This would mean that there'd be a difference between inherent requeriments to obtain the items within the cave (usually nothing, Hammer and Gloves and a way through spikes for Byrna chest, Pegasus Boots for the library) and to enter it (a lot of different things, including locations that otherwise have nothing interesting)

Sick kid may live in death mountain in place of a fairy, the hideout with all those chests may require Flippers, a fortune teller's house might contain Bombos, or the shop that needs hammer to enter might be something else now.
It'd work very well with the shop randomization too, as the players will likely find shops.

**Comment by ChristosOwen** [comment]
It's an interesting idea and as a standalone idea I do like it. It would require some (significant) work to the logic, since as locations would be randomized a lot of new functions would be needed. 

However the main community concern currently is the length. We're trying to be very careful with any changes which would make it even longer. This is why switching dungeon entrances and randomizing pot/enemy keys have been scrapped. I think the same would apply here too.

I think a separate project/version (door randomizer) would work very well and could include randomizing dungeon entrances, other overworld entrances like you mentioned, small and big keys from enemies and pots, where key doors are placed in the dungeons, etc. Super Metroid has two versions (door randomizer and item randomizer) so perhaps doing the same would be best for alttp as well?

**Comment by churine** [comment]
I've thought about it more and I agree. A randomizer that was designed to be complementary/compatible with this one would probably be the best approach, since that way it could also include options that would otherwise be too disruptive for a speedrun but useful on a more elaborate type of playthrough from a dungeon randomizer.
