### ISSUE TITLE
[v6] Permanently losable PoD

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#123]
Submitter: Alexander
Email: ancorwin@gmail.com
[v6]

The seed is C4156643

I believe I have used keys in such a way that it is no longer possible for me to win the dungeon. Actually, I'm pretty sure I can hammeryump my way to victory, but I assume seeds that allow you to get yourself stuck in a situation where hammeryump is _required_ count as bugs.

I assume this is clear, but I have no reason to believe this dungeon was unwinnable, only that it is losable, which is not nearly as bad but still not at all pleasant.

Also, I've been thinking a lot about randomizers and the algorithms for them, so I know that making a dungeon unloseable is an entire extra effort on top of making it winnable. Shit's hard, yo.

Thanks!

**Comment by BlueViper85** [comment]
On an initial check, this doesn't appear to be able to cause a key lock, though without playing or knowing which doors were unlocked it may be more difficult to tell.  Sent follow up e-mail to see if they could confirm what doors were unlocked.

**Comment by BlueViper85** [comment]
I've spoken with the submitter of this, and confirmed that he did manage to key-lock himself by unlocking the basement door early.  Leaving the only remaining small key in the maze room behind that locked door. I've mentioned to him that if the basement door isn't unlocked until absolutely necessary this won't happen in the future.  Do we want to do anything further with this?

I know there are some key-logic changes pending for Palace of Darkness, is this a scenario that we want to address in that update?  Alternatively we could remove the key door in the basement, but that seems like a bit too far.

**Comment by ChristosOwen** [comment]
Our options are:
1. Remove basement key door.
2. Remove keys from spawning in the 2 dark maze chests.
3. Never have any major items in the 2 dark maze chests or big chest.

I would choose option 1 or 2 if I had to, but would prefer "do nothing". I'll leave this up to Dessy.

Even if you do keylock from dark maze you can always hammer jump -- not ideal, but possible.

**Comment by ChristosOwen** [comment]
Actually there's another scenario we should consider: if dark maze has 2 small keys.

If you then unlock basement door, lobby door, bridge room door and big key door/spike room door then big key room/spike room would be unreachable, in addition to dark maze and big chest.

So the only ways to really prevent keylocks is to (remove basement door and limit dark maze to 1 key) or (limit dark maze to 0 keys). Thoughts on this?

The lesser of two evils is probably not allowing small keys to spawn in dark maze. You'd normally always be checking those areas for items other than small keys anyway so I don't see it being a case of "ok I have everything I need so going to skip dark maze" since you generally always (have to) do PoD early and while still looking for items. So that option really isn't that bad?

It also solves the initial issue too.

**Comment by KatDevsGames** [comment]
Why are people opening the doors in the basement early? That part I don't understand.

On August 31, 2016 6:40:18 PM EDT, ChristosOwen notifications@github.com wrote:

> Our options are:
> 1. Remove basement key door.
> 2. Remove keys from spawning in the 2 dark maze chests.
> 3. Never have any major items in the 2 dark maze chests or big chest.
> 
> I would choose option 1 or 2 if I had to, but would prefer "do
> nothing". I'll leave this up to Dessy.
> 
> Even if you do keylock from dark maze you can always hammer jump -- not
> ideal, but possible.
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/123#issuecomment-243924539

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ChristosOwen** [comment]
Palace of Darkness Summary
1. Prevent dark maze from having any small keys.
2. If 2 small keys are in dark basement, add logic/functions to prevent lamp from being in big key room, spike statue room or big chest.
3. Fix the lack of (bow) and (bow and hammer) in the logic by adding new functions:

First we need "'shooter room' is a small key" and this function needs to be added to all chests within the dungeon, except "shooter room". If the function is 'no' then "Bow" needs to be added to the logic for all those other chests. However "jump room [right chest]" and "statue push room" can be excluded since these already have "Bow" in their logic.

Then we also need "'jump room [right chest]' and 'statue push room' are not keys" and this needs to be added to all remaining chests within the dungeon, excluding "shooter room", "jump room [right chest]" and "statue push room". If it is 'no' AND the above "shooter room is a small key" is also a 'no' then "Bow and Hammer" need to be added to the logic for all of those other chests.

**Comment by ChristosOwen** [comment]
This had been addressed and will be working correctly in v7.
