### ISSUE TITLE
Small invisible follower bug

### ISSUE THREAD

**Issue by JonathanBergeron42** [Dessyreqt/alttprandomizer#124]
Good evening!

Thanks for the program, amazing. I was stuck on a small problem that I was able to fix reading around.

I got the third sword quite early, and I was thus able to fin the blue locked chest. Didn't unlocked it right away after finding it though, and left it somewhere.

After, I set out to do the 4th dark world dongeon, but the lady/boss was not in her cell. After a few more item, I find my way to 1rst dongeon entrace, but kiki was also missing.

After finaly completing the locked chest 'quest', the 4th boss repeared. Guess my following spot was taken.

Just to let you know, maybye something you'd want to fix. Kuddos!

**Comment by ChristosOwen** [comment]
Hi, glad you're enjoying randomizer!

Ah yes, this isn't the first time someone has had this issue. I think we'll make it so that the purple chest returns to its default position if you leave a screen without it following you. It's already removed if you s+q, or if you mirror from DW to LW without it following you. That way you'll never be able to leave it somewhere and forget!

**Comment by ChristosOwen** [comment]
For KarKat:

If it's NOT following you, then mirror, s+q and changing screens removes it. Not sure which of these are like this in vanilla, so may need to change 1, 2 or all 3 of them!

If it IS following you, then no changes are needed -- mirror, s+q and changing screens keeps it, as per vanilla.

**Comment by KatDevsGames** [comment]
That makes sense and seems reasonable. I'll add this to the bugfix queue.

**Comment by KatDevsGames** [comment]
Upon further thought, this fix, as described, is not possible given one of the two primary routes with the purple chest, leaving the chest near the t south of the haunted grove so as to be able to dash when obtaining the tree kid item while taking the dw purple chest route (so as to obtain the tree kid, circle of bushes, and bombos tablet items along the same path as the chest).

Not sure how to address this problem ATM or if we actually even should.

**Comment by BlueViper85** [comment]
In both of those situations I would think that leaving the chest where it is if you mirror without it solves the problem?  Except in the case of the Heart Piece cave below the grove.  Would entering that cave be enough to remove it, or can we make the game keep it in place in that situation?

**Comment by ChristosOwen** [comment]
Perhaps a really simple solution to this would be to return the purple chest to its initial location when you exit the overworld-->underworld or underworld-->overworld and it's **not** following you, otherwise leave it wherever you left it. This should resolve the initial issue of the maiden not spawning in Thieves' Town and have no other side effects?

**Comment by BlueViper85** [comment]
In that situation, we could still bring the purple chest to Kiki and to the Big Bomb in theory if the Big Bomb shop isn't one of the entrances that returns the purple chest (since entering a dungeon was discussed as the only trigger in Discord earlier)

**Comment by ChristosOwen** [comment]
This had been addressed and will be working correctly in v7.
