### ISSUE TITLE
Seed w/ Dead End @ Palace of Shadows

### ISSUE THREAD

**Issue by kevingrumman** [Dessyreqt/alttprandomizer#141]
The seed value in question is C481516234.

I am unable to proceed past a certain room in the Palace of Darkness that requires the Magic Hammer to eliminate a ring of moles (the room down the stairs from where you shoot the green one-eyed statue to move the wall). 

All other Dark World dungeons are inaccessible.  Since I do not have the Magic Hammer, I cannot hammer down the stakes near the bridge or around any warp portal to the Dark World.  I also do not have the Titan's Mitt to lift the heavier black rocks containing warp portals.

The Magic Hammer is in cave 056 (Dark World).  The only way to access this cave would be from the Turtle Rock warp portal, which I cannot open without the Magic Hammer and Titan's Mitt.  

The Titan's Mitt is given by the Flute Boy (Dark World).   I cannot access these area of the Dark World without the Magic Hammer or Titan's Mitt. 

Does anyone see another way to proceed?

**Comment by BlueViper85** [comment]
You got yourself an interesting seed here, but this is able to be completed.

I'm not one to immediately spoil things, but by the sound of it you should have the Hookshot (It's in the Palace of Darkness, if you didn't find it) and you're in the dark world.

From the pyramid go east one screen then follow the path up until you reach the area with a broken bridge.  Just past that area is a peg that you can hammer as well as a few stones.  These stones (or at least one, but I believe both) are able to be lifted with just the Power Gloves. Lift one of the stones, and just past it is a small gap in the barrier next to the river.  While you can't see it, use the Hookshot here and it will grab a hold of some stones on the other side and pull you across.  This will give you access to pretty much the rest of the dark world (except the Swamp of Evil).  This will allow you to talk to the Flute Boy and get the Titan's Mitts and then you can proceed with the rest of your adventure.

(Just to cover all bases here, on the lower level of Death Mountain, on the east side, you can hookshot across a broken bridge.  From there, there is a dark stone you can lift with the Titan's Mitts to access the Dark World.  Then you can use one of the caves to climb death mountain in the Dark World and access cave 056.  Since you can't use the Turtle Rock portal without the hammer, I thought I'd mention this now in case you didn't know about this portal to save you waiting for another response)

Thanks for playing! Good luck and have fun with the rest of your seed.

**Comment by kevingrumman** [comment]
Goodness.  I saw the gap while exploring earlier but couldn't see the stone on the other side of the river.  Thanks, I'll continue on!
