### ISSUE TITLE
Potential Softlock in Skull Woods

### ISSUE THREAD

**Issue by MayDonutLover** [Dessyreqt/alttprandomizer#147]
Seed: C7707957
First half of Skull Woods, I couldn't find the Big Key, and at the time, didn't have the Fire Rod.  So, while looking for the Big Key, I used up all my small keys.  And then, when I got the Fire Rod, I went back to Skull Woods, and went into the second half, where I promptly got the Big Key... and no small key for the first door in part 2.  I have explored every corner of the dungeon that I can, and I think I'm soft-locked.
I don't have any earlier save states, either.
I can submit pictures upon request.

**Comment by BlueViper85** [comment]
In the room right before you leave to go to the second half is a pot with a key under it, did you get that key, it tends to be easy to miss. Otherwise all keys in this dungeon are in chests. There are no chests beyond the key door in the second half so you have access to all the chests.

If that pot doesn't have your missing key, providing a save state in your current situation or the SRM file after saving and quitting would be good so we can identify where keys are and what has been used, but with what I can think of for this dungeon there SHOULD be a key available to you somewhere.

**Comment by MayDonutLover** [comment]
It had it.  Geez, I was having a heart-attack.  I've been working on this run for my YouTube channel.  Thank you!  It is VERY easily missable.

**Comment by BlueViper85** [comment]
Fantastic!  Glad to have helped, hope you're enjoying it.  Let us know if you have any more trouble!

**Comment by MayDonutLover** [comment]
I will!  If it wasn't for me streaming, I go through about a ROM a day.  I love the randomizer!  And I just want to make sure it's the best possible product.  Sorry if I seem like I'm missing small things/paths.  But I've burned through 10 other roms since I've last submitted an issue (which wasn't an issue after all), and they were all perfect!
