### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#151]
Submitter: Teddy Clancy
Email: teddyclancy@gmail.com
[v6]

I know this wasn't necessarily your intent and that this is more of a tool geared for speed runners, but I wanted to thank you from the bottom of my heart for all of the time and effort you have put into this.  ALttP is one of my all time favorite games and I have many fond childhood memories associated with playing this game.  Although I still play this game from time to time for fun and nostalgia, nothing has been able to capture the excitement and anticipation I felt the first time I played the game until your randomizer.  It was a humbling experience at first, I did not know the game as well as I thought I had, but every time I play I have to take a different route and every chest is a surprise (mostly pleasant except those damn 20 rupee and 10 arrow chests).  Now I run through it when I am feeling down and it cheers me up.  You have quite literally made my life better with this thing.  Thanks!

**Comment by ChristosOwen** [comment]
Wow! I'm glad there are people out there that enjoy this game (and the randomizer!) as much as I do. I can't take the credit - that would be our pioneer Dessyreqt who did a huge amount of work on his own initially, and continues to look after the logic and program itself - thanks Dessy - as well as Karkat who has done a huge amount of work implementing the various ROM edits you see - such as toggleable items and soforth - thanks Karkat!

And thank you Teddy for playing and enjoying this fine project and for taking the time to write your comment! If you ever get into livestreaming and/or speedrunning (the randomizer or otherwise) I'd definitely watch for the ride! ;)

**Comment by dorsey43** [comment]
I agree with Teddy, I can't tell you how much fun it is to play my favorite game of all time in a new light, and a different light each time for that matter. This week has been a blast! Thanks! 

-Mike

**Comment by BlueViper85** [comment]
Thank you all for the feedback! At this point I don't see a reason to keep the issue open. This message has been passed on to the people who deserved this.

Hope you continue to enjoy the ALttP randomizer and please let us know if you come across any issues, questions, or any additional feedback!
