### ISSUE TITLE
[v6] 1st dungeon darkworld to dark

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#154]
Submitter: sipfried
Email: sipfriedhemels@hotmail.com
[v6]
if you go to the dark part of the first dungeon(darkworld) the screen is full black . you cant see enemy,s or link

seed=c5713070
im using zsnesw as emulator

**Comment by BlueViper85** [comment]
You need to find the lamp in order to see in dark places in the Dark World.  The light world has caves and dark rooms lit up automatically.  The logic is setup so that you will never **have** to navigate these rooms to get to the lamp.

I looked at your spoiler log and confirmed that you can access the lamp.
