### ISSUE TITLE
[v6] Flute kid turned to wood already.

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#155]
Submitter: Philip
Email: thephilipwolfe@gmail.com
[v6]

I'm not sure what went wrong but the flute boy was already wood when I showed up to get his item and now I'm stuck. I saw that he's not supposed to turn to wood so I'm not sure what happened.

I'm happy to help however possible. Thanks for looking into it.

p.s. Sorry I don't actually have the seed name. I have the file still and I've been playing it but I accidentally deleted the name of the seed.

**Comment by BlueViper85** [comment]
This should only happen if you've already gotten the item from the flute boy. Have you checked the spoiler log to see what he has and are certain you already gotten it?

If so, can you provide the ROM and if possible the SRM file or a save state, as well as the emulator you are using?

**Comment by BlueViper85** [comment]
Realizing that an e-mail wasn't sent regarding this, and the way this issue was opened didn't automatically generate one I sent the following to Philip regarding this.  I'll leave this issue open until the end of the week (9/30) as it's only 9 days old, if no response is received I will close this issue.  Should the need arise I will reopen it and update with the appropriate notes

Good evening,

I'm responding to your issue about the Flute Boy turning to Wood in the ALttP Randomizer:
This should only happen if you've already gotten the item from the flute boy. Have you checked the spoiler log to see what he has and are certain you already gotten it?
If so, can you provide the ROM and if possible the SRM file or a save state, as well as the emulator you are using?

You can provide a response either via this email or by following the issue at https://github.com/Dessyreqt/alttprandomizer/issues/155

BlueViper85

**Comment by BlueViper85** [comment]
Philip sent me the ROM he is using.  The seed number was C2981603 which had 20 rupees and was likely obtained and not realized.
