### ISSUE TITLE
Turtle Rock Big Key chest may contain small key

### ISSUE THREAD

**Issue by SmashManiac** [Dessyreqt/alttprandomizer#164]
It's possible that a small key is randomized inside the chest that normally contains the Big Key in Turtle Rock.

The problem is that a small key is required in order to reach this chest by unlocking the door that leads to the connected pipe, and the unlocked path has no other usefulness. If all the other small keys have already been used, that chest is no longer reachable. Note that this doesn't prevent beating the game, but does prevent acquiring everything in the game.

While I did not stumble on this issue myself, I have some video evidence:
https://www.youtube.com/watch?v=moY8fVqaILI&t=27m10s

This issue is related to #134.

**Comment by BlueViper85** [comment]
If that chest has a key and all other doors are unlocked there's no reason to check that chest as it would only have a key. Obtaining this key would be unnecessary in that situation, as it doesn't hinder access to anything else except a pot with full magic.

I'm not sure I'm familiar enough with the key zones to say with any certainty that this doesn't create some sort of potential key lock of keys are late in the dungeon (laser room a bit before the boss comes to mind). I can think of scenarios it could happen, but don't know if those have been safeguarded or not.

Thanks!

On Sep 21, 2016, at 11:30 PM, SmashManiac <notifications@github.com<mailto:notifications@github.com>> wrote:

It's possible that a small key is randomized inside the chest that normally contains the Big Key in Turtle Rock.

The problem is that a small key is required in order to reach this chest by unlocking the door that leads to the connected pipe, and the unlocked path has no other usefulness. If all the other small keys have already been used, that chest is no longer reachable. Note that this doesn't prevent beating the game, but does prevent acquiring everything in the game.

While I did not stumble on this issue myself, I have some video evidence:
https://www.youtube.com/watch?v=moY8fVqaILI&t=27m10s

This issue is related to #134https://github.com/Dessyreqt/alttprandomizer/issues/134.

##

**Comment by SmashManiac** [comment]
I believe this issue is not a progression blocker. My concern is having players suspecting or falsely believing they might have blocked themselves, since they can't check the contents of that chest anymore to see if a required item is present in it or not.

**Comment by BlueViper85** [comment]
The spoiler log can be used to confirm what's in that chest, or alternatively having us check it for them to prevent other spoilers. While it could lead to spending additional time confirming that they got all the other chests, eventually they would hit a point and move on realizing either there is a key in that chest or otherwise not care.

The focus in this instance, at least in my opinion is randomization over ensuring every chest, even useless ones, are accessible.

On Sep 22, 2016, at 12:12 AM, SmashManiac <notifications@github.com<mailto:notifications@github.com>> wrote:

I believe this issue is not a progression blocker. My concern is having players suspecting or falsely believing they might have blocked themselves, since they can't check the contents of that chest anymore to see if a required item is present in it or not.

##

**Comment by SmashManiac** [comment]
It's a justifiable position. Personally though, I feel the frustration of stumbling into such a situation is not worth the extra layer of randomization. I'll let you guys be the judge.

If you decide to keep the current behavior, I suggest to document it as a preventive measure.

**Comment by Crystalchaos** [comment]
I can confirm this is an issue.  I had a small key spawn here but I need the big key to continue.  all chests up until this point have been opened and I have not obtained any dungeon items yet.  I can send my rom if you would like to check it.

**Comment by BlueViper85** [comment]
Cyrstalchaos, If a small key generated in the chest that contains the Big Key normally, it is the only chest behind that key door so you shouldn't have locked yourself out of completing that dungeon.  There's likely another place that has a key that you could've missed.  If you can provide a seed number we can validate that this seed is complete-able though so we can be sure there isn't a bug somewhere.

Most common places to miss a key:
- The pokey before the chain chomps room holds a key
- The room with the chain chomps has a chest if you push the lone block at the top of the block sets placed at the bottom of the room.
- The pokey before the key door to what is normally the big key chest also holds a key
- The laser room near the end of the dungeon (with chests near small pathways guarded by the eyes that shoot lasers)

**Comment by Crystalchaos** [comment]
missed the chain chomp room.  guess I don't know the game as well as I thought I did!  no need to send seed or rom you found my big key!  here I thought I was still pro at this game after all this time lol

**Comment by BlueViper85** [comment]
Glad I could help CrystalChaos!  Good luck and let us know if you run into any more issues.

**Comment by BlueViper85** [comment]
This has been discussed a bit further and we've agreed that since this chest having a key only blocks you from accessing that key and nothing else, this doesn't block you from progressing or completing the dungeon at all that no changes will be made in this regard.

We appreciate the feedback, and please let us know if you have any other thoughts or run into any further issues.

**Comment by nickretallack** [comment]
Oh darn.  I guess if you're going for "checked all locations" it might be impossible to achieve that.
