### ISSUE TITLE
Seed C0987188 unwinnable due to mirror being in place inaccessible without mirror

### ISSUE THREAD

**Issue by joeltucci** [Dessyreqt/alttprandomizer#170]
Hello, love your work.  Anyway, I tried running the game with seed C0987188 and got stuck, after looking at the spoiler log, I found out the reason is that the mirror is in a place that is inaccessible without the mirror, causing the game to be unwinnable.  The mirror is in Cave-056(dark world cave under boulder).  The problem with this is the only way to reach that cave is to use the mirror to climb up to the upper half of death mountain in the light world, which is obviously impossible without the mirror.

**Comment by BlueViper85** [comment]
The mirror is accessible, actually. You have access to the Titan's Mitts, Hookshot, and Moon Pearl which are all required.

Go to the mountain in the light world and walk up the first ladder then go right instead of left to the long ladder.  Follow the path right to the bridge. Stand near the edge of the bridge and hookshot across.

Follow this path and at the first chance take the path leading down/south and there will be a heavy (dark) rock next to a big formation. Pick that up to find a portal. This puts you in the dark world.

The cave system here will let you climb up the mountain and also access to a few chests.  Once you find your way to the top of the mountain you will be taken to the area with the big boulder to pick up which takes you to the cave where the mirror is.

Thanks and good luck!

BlueViper85

Sent from my iPhone

On Sep 25, 2016, at 9:25 AM, joeltucci <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello, love your work. Anyway, I tried running the game with seed C0987188 and got stuck, after looking at the spoiler log, I found out the reason is that the mirror is in a place that is inaccessible without the mirror, causing the game to be unwinnable. The mirror is in Cave-056(dark world cave under boulder). The problem with this is the only way to reach that cave is to use the mirror to climb up to the upper half of death mountain in the light world, which is obviously impossible without the mirror.

##
