### ISSUE TITLE
Seed C7896839 unbeatable

### ISSUE THREAD

**Issue by WindFox** [Dessyreqt/alttprandomizer#172]
Got pretty far, but I cannot complete it as I need a bow to beat a red Goriya in B1 of the Dark Palace and the bow is generated near the boss of the same dungeon. (There's no key available before this enemy.)

**Comment by BlueViper85** [comment]
Thanks for the report. Unfortunately there is a known issue with item placement in Dark Palace. This issue will be fixed in the next update.  This issue is being tracked in #123.

Closing this one as it is related to #123.  You can track this issue there if necessary.

Thanks for the report and let us know if you run into any further issues!
