### ISSUE TITLE
[v6] Anonymous Issue - Cannot progress

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#173]
Submitter: Blink
Email: stevencolumba@hotmail.com
[v6]

Hello,

This is Blink. I've been playing through the randomizer. Using seed C2348166, and I seem to be stuck. Misery Mire and Turtle Rock both require Quake to enter. But I have not had any luck finding Quake throughout the run. I can't progress due to that. I've already cleared all Light World Dungeons, and every Dark World dungeon except for Misery Mire/Turtle Rock due to that. How should I go about this? Just do a different run?

**Comment by KatDevsGames** [comment]
Upon inspection of your seed, I can confirm that this seed is solvable. 
If you wish to retrieve your spoiler log (if you decided not to generate 
it the first time) you can always retype your seed ID into randomizer 
and recreate the seed with the spoiler log option checked.

If you are still having trouble locating your missing item after 
checking the log, feel free to respond and someone should be able to 
assist further.

**Comment by BlueViper85** [comment]
I don't know if you sent an email to Blink or not, so to ensure this was seen I sent him a direct email based on Karkat's comment. While this can likely be closed I'm opting to leave this open for a couple days to ensure any responses can be provided and seen, and if a discussion needs to occur it can. 

The email:

Good afternoon,

Per your issue we have checked the seed and confirmed that Quake is accessible for you.

If you want to know where it is (or would prefer a hint instead of outright being told) you can email us, respond at the issue link at the bottom of this email, or you can check this yourself by generating the spoiler log by manually entering the seed number into the Randomizer and checking the "Create spoiler log" option then click Create.

A link to your issue page (GitHub account is required to respond there, but not to view it):

http://github.com/Dessyreqt/alttprandomizer/issues/173

If you have any questions, please let us know!  If we don't hear back from you in the next few days we will close the issue; however it can be reopened if necessary.

Thanks!

BlueViper85

**Comment by BlinkV** [comment]
Hey!

Thanks for the quick replies. I'll take a look at the seeding and see where I went wrong on this. Truly appreciate the help! =)

**Comment by BlueViper85** [comment]
Good luck! If you need any assistance finding the medallion just let us know!  Given that this is accessible, I'll close this issue; however, you can still add comments if you need anything else regarding this.  If you still have my e-mail you can respond to that as well.
