### ISSUE TITLE
Seed C2043636 unbeatable 

### ISSUE THREAD

**Issue by enhasiac** [Dessyreqt/alttprandomizer#181]
The issue stems from the Moon Pearl being the item to dig up in cursed grove, which requires the shovel.

The problem here is that you can't use he shovel while a rabbit, but in order to not be a rabbit you need the pearl, which requires you not be a rabbit to acquire by needing use of the shovel.

The moon pearl seems pretty prone to these sorts of bugs...

**Comment by BlueViper85** [comment]
The Haunted Grove is in the Light World.  The same location you get the flute from in the "vanilla" game (which does require accessing the same area in the dark world to get the Shovel, but that is not required if the Shovel is accessible elsewhere)  Since the shovel is accessible, and looking briefly at the rest of the log the other items all seem accessible suggesting that this seed is beatable.

If you have any other questions about this, please let us know!  Thanks for the feedback, I hope you continue to enjoy the randomizer.  If you see any other issues with the Moon Pearl (or any other item(s)) please let us know so we can ensure those get fixed in future updates.
