### ISSUE TITLE
Seed C3010535 unbeatable.

### ISSUE THREAD

**Issue by ghost** [Dessyreqt/alttprandomizer#188]
Reviewing the spoiler log there seems to be no way to beat this one. In order to get the Moon Pearl I need to light the torches in the Tower of Hera. The Lamp is in [cave-062] which it's chest cant be opened without the Moor Pearl. The Fire Rod is in [dungeon-D4-B1] which you can't get to without the Moon Pearl. Leaving no way to get the Big Key to climb to the top of the Tower of Hera.

Log attached here: [ALttP Random - C3010535 - 20161027.spoilers.txt](https://github.com/Dessyreqt/alttprandomizer/files/555268/ALttP.Random.-.C3010535.-.20161027.spoilers.txt)

Unrelated: I just wanted to say thank you for this fantastic mod.

**Comment by BlueViper85** [comment]
Thanks for the feedback, Zandabyte!  This is a known issue with the current version of randomizer. This issue is being tracked in #182, so I will be closing this issue; however, it is still open and being tracked there and this issue will be linked.

Thanks again, and I hope you continue to enjoy randomizer!  Let us know if you have any more problems, questions, or suggestions!
