### ISSUE TITLE
Difficulty setting feature req/suggestion

### ISSUE THREAD

**Issue by the-bacon-sword** [Dessyreqt/alttprandomizer#195]
Do you guys make note of the tricky ones reported unsolvable but then later solved?  Perhaps that's the first step towards difficulty levels.  If you start cataloging which ones require a string of items, and only one possible path to get the first, You could change the "casual" difficulty to "new/random", and add "hard" and "easy" that would pull from a list that gets added to each release.  It could also potentially pull the list from a server/cloud just as it checks for updates for more frequent updates.

This way, the gamer knows they're getting a difficult one.  It would essentially be crowdsourced

**Comment by BlueViper85** [comment]
There is a spreadsheet we have with a list of seeds and their difficulty (as judged by the person adding it to the list) more as a means of people to look at if they want a specific sort of seed.  The link to this exists in our Discord channel.  I'm not in a position where I have discord access to provide a link to the server or the sheet here right now, but I can provide one later (if someone doesn't beat me to it).

That being said, I'm of the opinion that leaving it as currently planned with a "casual" and  "glitched" difficulty (coming in a future version). Simplifies the randomizer and can help reduce the bugs and subjectivity of what's easier or harder.

We do keep an eye on general feed back and the issues that are reported and make adjustments if necessary to either the logic or updating the helpful information found on the download page.  Otherwise, asking for help is an accepted form of assistance for the more obscure cases

**Comment by jakj** [comment]
ALTTP Seed Share: https://docs.google.com/spreadsheets/d/1HqX6S9XDw4BswiDcznx0b8xWedHRT6qmRdpteZ9Qsi0/edit#gid=0
