### ISSUE TITLE
Impossible seed C7911263

### ISSUE THREAD

**Issue by Sagerninja** [Dessyreqt/alttprandomizer#196]
Alright, maybe someone else can see something i can't but as far as I can tell,  I cannot get into the misery mire area. The misery mire area needs titan's mitts to get in. But, the titans mitts are on death mountain in the dark world after the bumper  cave which needs the magic mirror. The magic mirror is in misery mire in cave 71 which is in misery mire. Is this actually doable or is the seed impossible to complete? Thanks in advance.

**Comment by jakj** [comment]
Why do you say doing the bumper cave requires the magic mirror? It requires only the cape, and the hookshot makes it easier but you can wiggle around the pit while grabbing the pot without the hookshot too. Pass the bumper with the cape, go outside, get your mitt.

**Comment by BlueViper85** [comment]
As jakj said, the bumper cave does not require the mirror.  You will need the power gloves and the cape to access and pass the cave though (as well as the moon pearl and hammer and/or hookshot to get there)

If you don't have the hookshot, after entering the cave you can wlk along the left edge right up against the wall to walk around the hole and then use the cape to get past the bumper.

Once you leave the cave the mitts will be right there in the open dark world, no mirror is needed.

Keep in mind that this cave is NOT on top of the mountain.  It is in the same location where you would normally use to get on top of the mountain on your way to the Tower of Hera for the third pendant in the original game.  Just in the dark world instead of the light world.  If that doesn't help, it's the cave one screen south of where the lumberjacks, their house, and the tree they are cutting are located.

A quick review of the rest of the spoiler log for this seed shows that this seed IS beatable.
