### ISSUE TITLE
[v6] Language issue with randomized rom

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#197]
Submitter: TheFriskiestFrisk
[v6]

The randomized ROM is all Japanese for me.

**Comment by BlueViper85** [comment]
No email provided to respond directly. Putting a see here:

This is by design, and the reasoning is explained in he informational download page.

Why is the game in Japanese?
This randomizer uses the 1.0 JP version of the base rom because it is what is primarily used in speedrunning ALttP. Here are some of the features of this version compared to the English version:

Faster text speed. This is very noticeable during the introduction.

After getting the Pegasus Boots, pressing Y + A will allow you to use an item and dash at the same time. For a clear example of this working, try hammer dashing at the bridge leading from Dark Palace to Swamp Palace.

You can jump down from a wall of which you are partially inside. This is most useful above the section of Turtle Rock that leads to the Mirror Shield.
In an area where you can't use the Magic Mirror, you can make pushed blocks disappear by trying to use it while pushing the blocks.

You can enter the Exploration Glitch in Tower of Hera by falling down the rightmost hole on the 3F, then jumping right from the wall.
