### ISSUE TITLE
Flute and Shovel Issue

### ISSUE THREAD

**Issue by tgamergrl** [Dessyreqt/alttprandomizer#208]
So I have discovered an issue I am surprised hasn't been brought up yet. I had managed to find the flute early on and later I found the shovel. The shovel covered up the flute in the item list, so I figured to fix this I needed to go and get the item in the grove, so I went and got it, but I still have the shovel and no flute anymore.

**Comment by BlueViper85** [comment]
Per Issue #93, there is a known bug with certain emulators (specifically ZSNES and SNESGT) and the SRAM Trace option where immediately upon obtaining the shovel/flute/mushroom/powder the option to switch to it's related item became available despite having no obtained it. That particular bug will be fixed with the next version of the ALttP Randomizer.  

Can you please confirm if you selected the "SRAM Trace" option and what emulator (including the name and version) you are using?

**Comment by tgamergrl** [comment]
I am using SNES9X emulator, and no I did not use the "SRAM Trace" option, not sure what that does so never selected it. I am using seed C4593879 if that helps any. With what you said, the thing is, since these are part of the randomized table, using the shovel to dig in the grove or the mushroom to get the powder, you sort of need to be able to do those so to get whatever item is hidden behind them, because what happens if turning in the mushroom happens to give you the boots or something else that is super important. But hopefully that issue is something you guys can figure out how to fix, though probably easiest option would be to make those items static and not randomized any.

**Comment by BlueViper85** [comment]
I think I may have mis understood your original issue, so my apologies there.

The randomizer includes a new feature for the red/blue boomerangs, mushroom/powder, flute/shovel and the bottles. You can press Y to switch between these items since they occupy the same a lot. When you select each item in the item screen you will see a Y appear above the item to the right.

For the bottles it will switch between all four bottles and you can press X to see the normal full list of bottles.

**Comment by tgamergrl** [comment]
Ah that makes sense now, I missed the marker for it and just saw that it replaced the item and thought it had de-evolved the item. Thanks for explaining that.
