### ISSUE TITLE
[v6] C3005138 (bug)

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#212]
Submitter: Jack
[v6]
Hello,

First I would like to say thanks for the "randomizer" i am having a lot of fun with it. But Im stuck... I cannot find the hookshot anywhere... i've been everywhere and I can only feed money... When I thought that i would find the hookshot at lvl 7 i found a second boss key (at the chomps where you have the switch). Since i cant find the hookshot anywhere I cant finish lvl 2 and 5. I also notice at the zora's when i first went there. There was a red ruppee where you find the heart piece... I went there again and found the bug net... Is this normal? I also found an extra key in Misery Mire and the first time that I went to lvl 7 i had to use bombos to get in... Today i was playing and the simbol to get in was quake.

Thanks for the randomizer!

**Comment by BlueViper85** [comment]
If you are having trouble finding an item, you can put the seed number into the randomizer manually and select "Create spoiler log" to generate a txt file that tells you where every item was placed.  This spoiler log references maps found at the bottom of the [randomizer page](http://dessyreqt.github.io/alttprandomizer/), if you need a visual cue of which cave is which.

Hookshot is in the "Wall of Caves" on Death Mountain which is accessible with the power gloves and the hammer.  Need to use the cave next to the bundle of rocks with the fairy to climb down to the bottom of the mountain and access them that way since you don't have the hookshot.

![image](https://cloud.githubusercontent.com/assets/12190332/20565586/b98da7fc-b157-11e6-8a62-13c78d46c1b1.png)

According to the spoiler log only one Big Key spawned in the usual Big Key location in Turtle Rock.  Chain Chomp room had 20 rupees.  I'll leave this open to verify what happens if I try this myself.

The rupees instead of the bug net sounds like one of the graphical glitches we've seen.  I'll confirm this when confirming the Big Key concern in Turtle Rock.

Misery Mire had one (entirely unnecessary) locked door removed making it easy to have an extra key.

The medallion required to open Misery Mire and Turtle Rock are both randomized.  Either dungeon can require any of the three medallions (sometimes the same medallion for both) so that is completely expected.

**Comment by BlueViper85** [comment]
Ran through the seed enough to get to Turtle Rock to confirm the two things I mentioned in my previous comment.

-The Zora Heart piece location showed a red rupee (as expected, based on the spoiler log) and was a red rupee when picked up
-The chain chomp room had a red rupee when obtained before the big key
-The chain chomp room had a red rupee when obtained after the big key (since they phrased it as a "second big key"

Hookshot location provided in previous comments, no bugs seemed to exist in my testing.  Without further contact information no additional details can be given.  I will close this issue for now; however, if new details are found they can be provided as new comments and this can be reopened if necessary.
