### ISSUE TITLE
Problem in dungeon D2 - Unreachable key after flooding

### ISSUE THREAD

**Issue by Radagast81** [Dessyreqt/alttprandomizer#218]
In the 2. dungeon of the dark world there is a key in the area that can be flooded in the room left to the big chest. If you flood the room prior to obtain the key there seems to be no possibility to get that key and therefore you could produce a lock. Perhaps save und reload solves the problem (i have not verified this yet) but it would be nicer if reentering the dungeon solves this issue too (just reset the button states on reentering).

**Comment by BlueViper85** [comment]
This issue is addressed under the "bugs that wouldn't come up during normal play" section in the randomizer download page. If you haven't read this whole section yet, it is worth reading for future plays of the randomizer.

If you collect the key in the big chest room in the Swamp Palace (due to having hookshot earlier than normal), then use that key on the top left door of that room, you can cause a soft lock due to being unable to access that key. In randomizer, moving one screen on the overworld away from the entrance to Swamp Palace will reset the water both around Swamp Palace, and the water that would cover those keys.

Thanks for the feedback, please let's us know if you have any further trouble!
