### ISSUE TITLE
No Flashlight in Dark Dungeon

### ISSUE THREAD

**Issue by Rynyl** [Dessyreqt/alttprandomizer#219]
A friend and I were playing the first Dark World Dungeon and noticed that there was no flashlight in any of the dark rooms. Some sprites, such as the hammer and the switch globe, were still visible, but everything else was completely (could not see enemies, Link, anything else on the floor, etc.). It's only in this dungeon; every other cave works fine. I have another game going on another computer that has the same issue. I've tried multiple emulators (using the ones available through RetroArch - bsnes and Snes9x) and the problem still persists.

At the time, we had the fire rod. Using it did nothing as there are no lantern pires in some of the rooms. I found someone who submitted a similar report (#204), but it was closed with only a comment about it being a design feature. There should at least be a flashlight around Link to see your immediate surroundings ([like this](https://i.ytimg.com/vi/mRMWlMADTDs/maxresdefault.jpg)); I don't think the room is supposed to be pitch black.

I've attached the ROM. The seed is C3070781.

[ALttP Random - C3070781.zip](https://github.com/Dessyreqt/alttprandomizer/files/623391/ALttP.Random.-.C3070781.zip)

**Comment by BlueViper85** [comment]
This is not an issue with the seed, rom, or emulator. This is a design of the game. In the light world you can see in dark rooms without the lamp, in the dark world you cannot. To see in the dark rooms of the Dark World dungeons you must find the lamp in order to see. The lamp will not be in a place that requires passing a dark room (like the one in the Palace of Darkness). Just need to keep searching.

Per the download page for the randomizer:

In the light world, you don't need the Lamp to see in the dark.

While not explicitly calling out the DW, it implicitly covers that DW does require the lamp to see in the dark.

Thanks for the feedback and good luck!  If you need more help or find anything else that may be a problem, please let us know!

I will close this issue for now. If you have any more questions about this issue you can comment here even while closed. If a bug is identified it can be reopened.

**Comment by Rynyl** [comment]
That's...odd. A rather esoteric choice by the original game designers, seeing you can't even finish the 3rd dungeon and get into the dark world without the lantern (you need it to light spires to get the big key). 

But I don't expect an answer why that is, only that it isn't a bug or anything. I didn't understand the original reply from #204, but now I do. Thanks for the swift reply! I'll remember that for future runs.

**Comment by Rynyl** [comment]
OH WAIT, I understand now. You normally need the lantern to see in any dark room normally, but you guys with the randomizer made it so you don't need it for caves in the light room.  

I got it now. I am smart. Fantastic. Thanks!

**Comment by BlueViper85** [comment]
Correct! In fact in the normal game you can't move the mantel during the initial escape sequence (with Zelda) without the lamp.

We removed that requirement so lamp could be anywhere but made the cone appear in Light World to allow the lamp to be in dark world while not negatively impacting eastern Palace (first LW dungeon) since that was the only place it is required to see in LW.
