### ISSUE TITLE
Potential Softlock/Lost Seed Number

### ISSUE THREAD

**Issue by Rynyl** [Dessyreqt/alttprandomizer#224]
Hopefully this is a legitimate issue and me not being stupid. 

Currently, I am at the point in the game where you have access to dungeon 1 in the Dark World. I cannot find the hammer, nor either of the power gloves. Because of this, I can only access a small portion of the Dark World (namely, Death Mountain and the area where the Palace of Darkness is). Getting across the bridge to access the rest of the DW requires the hammer, and the other portals require gloves to move the rocks. I also cannot get the master sword to check the tablets where the medallions usually are because I can't finish dungeon 2 without either set of gloves.

I'm about 90% certain I have opened every chest that I can access at this point in the game, but I still cannot find any of those three items that would open access to the rest of the Dark World and continue the game. Normally, I would "cheat" and look at the spoiler log at this point before submitting an issue, but for some reason (whether because I deleted it out of cockiness or the program didn't put it in the file name), I don't know what the seed number for my ROIM is. 

So, is it possible my game is softlocked? And/or Is there a way to recover the seed number for my file so I can generate the spoiler log for my file? Thanks!

[ALttP Random - .zip](https://github.com/Dessyreqt/alttprandomizer/files/629191/ALttP.Random.-.zip)

**Comment by BlueViper85** [comment]
If you have access to the dark world near Palace of Darkness you probably have (or at least have access to) the hook shot. From the pyramid, walk east then north and follow the dirt trail. You'll eventually see a small break in the wall to the water (look for an arrow out of the grass on the other side). Use the hookshot there to get across and access other parts of the dark world.

As for the seed, it's embedded into the ROM. If you are using SNES9x as your emulator check the yellow text that appears when you load the ROM. Top row left side shouldn't have a block of text that starts with a C and followed by 7 numbers. That is the seed. Type that into the Randomizer and check the option for he spoiler log to see it (if you want).

Barring all that, let us know what items you DO have and we can help.

Someone here with access to the computer may be able to load your provided ROM and provide the seed and/or check the spoiler log for possible issues. I do not have computer access myself at the moment otherwise I would.

Let us know what happens or if you need more help!

**Comment by Rynyl** [comment]
Okay, well, now I really don't know what happened because now my save file is gone (user error). But at any rate, I did have the hookshot, so I would have been fine. I didn't even think to try using the hookshot to cross the river.

Thanks for the help. Out of curiosity, is there like a subreddit or forum where I can ask these type of questions so I don't have to submit it as a bug report?

**Comment by BlueViper85** [comment]
Well that's unfortunate.  For what it's worth, many emulators require the save file to match the ROM file name exactly. Could be something to check?

In any event, the best place would be to join the ALttP Discord and pop into the Randomizer channel and you can ask questions there. https://discordapp.com/invite/3Bsfnwk
