### ISSUE TITLE
Mothula sword damage

### ISSUE THREAD

**Issue by sohowsgoing** [Dessyreqt/alttprandomizer#227]
Unable to inflict any damage on Mothula with Level 4 sword (golden sword).  This is a known issue with the original game.  Would you be able to fix this?  

Similarly, spin attacks with the tempered sword also do not work.

**Comment by BlueViper85** [comment]
The gold sword will damage Mothula in the next version of the Randomizer (No ETA).

This is the first I've heard of the sword spin with tempered sword though. I will leave this open until someone else with information on that can speak.

**Comment by sohowsgoing** [comment]
Awesome!  Thanks!

**Comment by ChristosOwen** [comment]
Yeah the way damage classes work is fighter spin = master slash; master spin = tempered slash; tempered spin = gold slash = gold spin (since everything except 1 enemy takes the same damage from gold slashes and spins). 

For v7 attacks with tempered sword (slashes, spins) and gold sword (slashes, spins, pokes) will do tempered slash damage, i.e. the highest damage possible to inflict on Mothula, 1/4 of his HP. Tempered pokes will remain unchanged doing master slash damage.

**Comment by BlueViper85** [comment]
Thanks for confirming, Chris!  Closing this issue.
