### ISSUE TITLE
C1601462 stuck

### ISSUE THREAD

**Issue by draguscloud** [Dessyreqt/alttprandomizer#237]
Can't finish this seed since Hookshot, Mirror, or Titans Mitt.
Hookshot and Mitt are at the Death Mountain caves. needing mirror or hookshot.
Mirror is at teasure game which needs hookshot or mitts to reach.

Unless I missed something I don't see how to beat this seed.

[ALttP Random - C1601462.sfc.spoilers.txt](https://github.com/Dessyreqt/alttprandomizer/files/665017/ALttP.Random.-.C1601462.sfc.spoilers.txt)

**Comment by BlueViper85** [comment]
This is one of the more challenging seeds, but it does appear to be beatable.

Here's a general idea of the route you need to take:

-Get a bottle (empty or otherwise), the cape, moon pearl, power gloves, ocarina (and activate it), 
-Use the cape to bypass the barrier to Agahnim's tower and go to the dark world and walk up to the catfish where you normally get the quake medallion.  This gets you the hammer
-Save and quit to get back to the Light World
-Go to the town and warp to the dark world (go through the forest and come down to the warp from the north) use the hammer to get to the portal and get the mirror from the chest game.
-Use the mirror to get to the Light World
-Fly to the mountain (or walk) and navigate it like you're going to the Tower of Hera
-Walk the top of the mountain to the right side and use the hammer at the bridge
-Climb/jump down on the eastern side
-Go to the wall of caves and get the Titan's Mitts.

From here you can use the portal for Turtle Rock to get to the dark world OR there is a dark rock on the lower-eastern side (near the cave entrance for the Wall of Caves) that will take you to the dark world there as well, giving you access to the Hookshot.

**Comment by draguscloud** [comment]
I wasn't aware of those pegs. Thanks.
