### ISSUE TITLE
Seed C9993870 Hyrule Escape Key Zone Error

### ISSUE THREAD

**Issue by miketrethewey** [Dessyreqt/alttprandomizer#254]
Seed C9993870 during Castle Escape, I can manage to get stuck via keyzones.

```
Hyrule Castle Escape
--------------------
[dungeon-C-1F] Sanctuary..................................................................Map
[dungeon-C-B1] Escape - final basement room [left chest]..................................10 Arrows
[dungeon-C-B1] Escape - final basement room [middle chest]................................100 Rupees
[dungeon-C-B1] Escape - final basement room [right chest].................................20 Rupees
[dungeon-C-B1] Escape - first B1 room.....................................................Bottle (Green Potion)
[dungeon-C-B1] Hyrule Castle - boomerang room.............................................3 Bombs
[dungeon-C-B1] Hyrule Castle - map room...................................................Key
[dungeon-C-B3] Hyrule Castle - next to Zelda..............................................Hookshot
```
I get key from Map room chest, ignore guard (who happens to hold a key), open door and proceed. I get key from guard in Boomerang room, proceed to Zelda. Pick up Zelda, proceed to movable shelf. Go through movable shelf, with no keys, door closes behind and no keys before locked door, resulting in softlock.

Is this an instance of "hey dude, you failed to kill all the dudes to get keys" or an actual case that should be checked for?

**Comment by BlueViper85** [comment]
There aren't any good places to put keys after the shelf since there's only one chest (not counting the three at the end that require bombs, which won't be guaranteed to be available)

Since this is a case of missing a known, static/constant key this would be chalked up to user error. Since not much can be done to fix it. It's also early enough in the game that a restart isn't unreasonable or too costly.
