### ISSUE TITLE
Idea for v8

### ISSUE THREAD

**Issue by Radagast81** [Dessyreqt/alttprandomizer#261]
Hi guys,
i have a simple idea for v8. As I read you plan to split the 70 bomb upgrade to some smaller upgrades according to the steps of the fairy. So why no going one step further and reduce the initial bomb capacity to zero and add another 10 bomb upgrade to the itempool.
This way you need to find at least one bomb upgrade before you can use bombs. Which will lead to some more complexity...

Kind regards,
Radagast

**Comment by BlueViper85** [comment]
I get where you're coming from with the concept, but it seems like adding difficulty for difficulty's sake which really isn't a goal of Randomizer.  This also adds a lot of needless complexity to the logic because now bomb-able walls have to be taken into consideration when placing items.  We want to keep randomizer as close to "original" as possible, while making improvements to speed (removing text).  1/4 magic is about as close as it gets to "non-vanilla" but the code already existed, just wasn't active.

There are plans to randomize (to some degree or another) shops and enemy drops which could potentially help or hurt your ability to get bombs as early as we can today with the shop in the Kakariko Village.  Depending on how it's implemented, of course.

**Comment by KatDevsGames** [comment]
I expect this kind of thing will be quite popular in plandos. The rom supports this officially even if randomizer doesn't use it.

**Comment by Radagast81** [comment]
Yeah i myself like the unexpected challanges or different strates i have to use when specific items are missing and it would be fun to see what comes from missing bombs. Buts it's only a little idea of mines if it conflicts with the original idea of the randomizer you don't have to take it. But for my opinion that doesn't conflict with being far from the original as it is barely the same only that you more or less add the bombs to the key items instead of asuming them for free...
