### ISSUE TITLE
Fix Short Range Boomerang/Hookshot (Vanilla Gameplay Issue)

### ISSUE THREAD

**Issue by Nicholas-Steel** [Dessyreqt/alttprandomizer#263]
Demonstration of the invisible laser emitted by guards when they search for you: https://www.youtube.com/watch?v=CH0D7aGaBRg

Example of vanilla game bug: https://www.youtube.com/watch?v=ZkkICA8hjWQ

If either Boomerang or the Hookshot collides with this beam that the soldiers invisibly emit than the item will act like it hit something and prematurely return to you. This is quite aggravating whenever it occurs as you expect it to hit the enemy, not stop prematurely mid-air and return to you!

So this feature request is to make these items not collide with that beam the soldiers emit when they are scanning for Link.

**Comment by Nicholas-Steel** [comment]
Example of the problem: https://www.youtube.com/watch?v=ZkkICA8hjWQ&feature=youtu.be

**Comment by ChristosOwen** [comment]
Even though this is vanilla behaviour it is annoying when it happens so I don't mind if it's fixed.

**Comment by ChristosOwen** [comment]
Decided not to implement this.

**Comment by Nicholas-Steel** [comment]
Disappointing that THIS is considered too different from vanilla but boss changes aren't.

**Comment by ChristosOwen** [comment]
If you want to spend the time working out how to fix it then go ahead, it's such a low priority, exists in vanilla, is very rarely a problem, and adds nothing to the randomization. This isn't a remastered version where we fix every known bug with the original. If you're annoyed because blue balls and warps were removed then I have no sympathy. This project was created originally to be raced by speedrunners. The very opening sentence written by Dessyreqt on the download page is:

"This is a simple program that moves around items in the Legend of Zelda: A Link to the Past (ALttP). It is used for racing the game."

It continues to be developed with speedrunners and racing in mind. We've spent a considerable amount of time developing the Casual version so non-speedrunners can play without any softlocks but while also having the optimal randomization possible. 

I've never seen you say thank you once. You're so negative and pedantic about everything, on here and in Discord. If you don't have something constructive or positive to say then please say nothing and stop being so entitled.

Thank you.

**Comment by Nicholas-Steel** [comment]
Note: I removed my post preceding ChristosOwen's post which critiques me.
