### ISSUE TITLE
Add ability to generate a ROM with a specified complexity

### ISSUE THREAD

**Issue by JingerTV** [Dessyreqt/alttprandomizer#282]
It would be great to choose the complexity instead of creating 20 seeds for the whised complexity.

**Comment by Radagast81** [comment]
The only way to accomplish this would be to do exactly what you do now manually automatically. Create seeds unless you get a seed that fits your requirements and discard the others. Otherwise the given complexity will affect the algorithm of the randomizer and this must not happen...
One could add such a filter on the seeds, but i think it's easier just to create a bunch (put the complexity token as prefix to the filename so you can order them by complexity) and then copy the fitting seeds.

**Comment by thejoshwolfe** [comment]
This idea is something I've been thinking about for a while (since before the complexity analysis was implemented). It would require a fundamentally different algorithm than the one that currently exists.

Regardless of what algorithm is used to assign items to locations, the details of how it works are significant to developing a strategy for blind racing (which is a primary purpose of this project). As it is now, the algorithm is not really explained anywhere in the documentation, and players must either: a) read the code to see how it really works, b) play a bunch of seeds to get a vague sense for how it works, or c) just guess how it works. I'm thinking that a mix of b and c are the intended way to develop a strategy.

I've been attempting to read the code to figure out exactly how it works, and it's pretty tricky. There are many possible algorithms for assigning items at random such that the game is beatable, and the currently existing algorithm is just one of them. Each algorithm will have slightly different probability distributions for where items are likely to be, and being able to analyze that probability during a blind race is a significant advantage.

It could be possible (although not necessarily a good idea) to have an option in the randomizer to select an algorithm to use. (Sorry for the rambling above; I'm finally getting to the point of all this.) With this option in place, we could have an algorithm that targets a specified complexity or specified range of complexities. I believe all of this would be necessary to really implement this issue.

My vote is that we do all of that. I think it'd be really interesting to play a bunch of maximum complexity seeds, or even just being able to play around with alternate generating algorithms. At the very least, I'd like to (if no one else wants to) document the current algorithm so that hardcore probability enthusiasts can make more accurate predictions of where everything is likely to be without doing b or c above.

**Comment by Radagast81** [comment]
The point is simply that it's necessary for races that the same seed number has to result in the same game, so you don't want to have different algorithm or you have to create a "difficulty" for every algorithm you use. More precise every option that affects the algorithm has to be hidden in the difficulty and that is a number you want to keep as low as possible.
Furthermore a knowledge of the algorithm grants no knowledge where the items are (if they are really put random) it's only the restriction on where an item may be located that makes the difference and doesn't change with the used algorithm...

**Comment by KatDevsGames** [comment]
Just taking a moment to point out that a correct randomization algorithm 
should provide the exact same distribution as any other correct 
algorithm. If implemented properly, the only difference will be which 
number corresponds to what placement.

**Comment by thejoshwolfe** [comment]
> a correct randomization algorithm should provide the exact same distribution as any other correct algorithm.

You're saying that a "correct" algorithm should generate a mapping from item to location with an *even distribution* over the set of all possible (and winnable) mappings from item to location? I don't know if i would call this a "correct" algorithm, maybe an "even distribution" algorithm, or a "regular" algorithm or something like that. Do you think the existing algorithm actually does this? I really can't tell.

I'd like to argue that an even distribution is not necessarily the best goal for an algorithm like this. I think that every winnable mapping *should* probably be a possible output from the algorithm, but the algorithm could be biased towards more interesting/difficult/easy/complex/ironic/etc mappings, and that shouldn't make the algorithm "wrong" or anything.

I think that proving or verifying that the current algorithm is an even distribution would be a pretty difficult exercise, and it would, of course, first require understanding how the algorithm really works. I haven't yet reached that understanding, so maybe I'm just ignorant of the situation.

**Comment by thejoshwolfe** [comment]
Are two mappings considered equivalent if the only difference between them is that two identical items are swapped? For example, a red rupee and another red rupee? I think those should probably be considered the same mapping, but I'm pretty sure the current algorithm doesn't take that into account. This seems like a clue that the algorithm isn't really evenly distributed.

Or maybe I'm over thinking this, and probability isn't really as hard as I'm thinking it is. Again, I still feel pretty ignorant of how the existing algorithm works.

**Comment by Radagast81** [comment]
Correct randomization algorithm just means that the algorithm itself can create each valid permutation of the items. It doesn't say anything about distribution.
The randomizer itself will not be able to create every possible permutation, cause the number of permutations is by far bigger than the number of possible seeds.
Nonetheless there should be a sufficient number of seeds for any condition you might think of...

**Comment by thejoshwolfe** [comment]
Here is an algorithm that would create an even distribution:

1. Ignore the logic rules about what can be where and simply randomize the locations of everything with an even distribution.
2. Test the mapping to see if it's possible to win. If not, start over.

This is a pretty terrible algorithm, because it can take an arbitrary amount of time to complete, but it would at least produce an even distribution.

> the number of permutations is by far bigger than the number of possible seeds.

Right. Before eliminating impossible permutations, `141!` is  243 digits long, which is much bigger than the 7 digit seed we're using. I don't think humans will notice limitations imposed by the size of the seed if it's as large as it is now.

But humans can notice biases if, say, the late game chests tended to be rupees. I can imagine a naive algorithm that would have that bias, and I can imagine lots of other algorithms that have other kinds of biases too. I think the current algorithm probably is biased in some way, and I'd like to analyze what that is.

**Comment by nickretallack** [comment]
What's the range for the complexity number?  The vast majority of seeds I generate get a 6 or 5, but I've managed to get a few rare 7s and 4s occasionally.  Is it possible to get an 8?

How does it determine complexity?  Depth of the causality tree?  Couldn't you design an algorithm whose goal is to create a deep tree?  It would be less random, but possibly more interesting.

What's the most interesting game you can create?  One that requires you to tackle the ice temple with bombos instead of the fire rod, enter misery mire with the pegasus boots instead of the hookshot, enter the desert palace without the book and complete it without the glove, do as many dungeons as possible in reverse order, etc.  You could give a "strangeness" score to things like this.  Putting an item you'd normally expect to have in the dungeon as the item the boss gives you guarantees this sort of strangeness.

Anyway, I love this game and I'd love to try a harder, stranger variant that forces me to use weird techniques.  I'm not prepared to exploit glitches yet though.  Anyone got some highly complex seeds to share?

**Comment by ChristosOwen** [comment]
It sounds like what you're after are custom randomizers:

http://tinyurl.com/zjtarrl

Complexity is essentially a measure of linearity, i.e. how many iterations there is of "item A is required to reach item B which is required to reach item C..." etc.

**Comment by ChristosOwen** [comment]
The idea of complexity no longer exists due to new fill algorithm. Be sure to check out the live web version: http://vt.alttp.run/
