### ISSUE TITLE
[v7] Arrow and Bomb Capacity bonus gives bonus of 1 instead of 5

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#283]
Submitter: Scygnus
[v7]

Game seed is C5522583, Casual Difficulty, also set heart beep to quarter speed, though I'm not sure it would matter.

The fairy in the lake, when paid, only gave a bonus of 1 to my bomb and arrow capacity per 100 rupees. I did not cap out the arrows, but the bombs capped out after the normal number of uses, leaving my max total at 17 instead of 50. I also experienced the Lumberjack Tree sprite bug, just in case examining my game seed helps to solve that issue.

**Comment by Scygnus** [comment]
Okay, nevermind, I found the seventy arrow  upgrade in a chest. I presume the 1 upgrade is intentional because you couldn't shut it down all the way... I assume you replaced instances of regular arrows and bombs in the item pool for this. Sorry to bother, then.

**Comment by ChristosOwen** [comment]
You're exactly right. We've added max 50 upgrade for bombs and 70 upgrade for arrows. The faerie in the pond of happiness has been reduced to 1 to prevent getting the limits much higher. The next version will change this slightly so the capacity upgrades are split over six +5 and one +10 upgrade for each of bombs and arrows instead of instant 50/70. This mirrors the regular fairy much better.

Then in v9 we will be overhauling the 3 faerie upgrade fountains so the functionality of it will change then too.

Going to close this for now as no immediate action required. Hope you continue to have fun! :)
