### ISSUE TITLE
[v7] Arrghus Immun for Lv 1 sword oO

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#288]
Submitter: Tantalus-X
i have used lv 1 sword for boss Arrghus make not damge ^^

**Comment by BlueViper85** [comment]
To beat Arrghus (and many of the Dark World bosses) with the level 1 sword you need to use Spin Attacks instead of slashes because the slash is not strong enough, but the spin attacks are more powerful. In the case of Arrghus's first phase (with the puffs), charge the sword before using the hookshot to pull the puffs away, then release the sword spin when the puffs are near you.

Alternatively, you can use the hammer to deal damage, but you will have to pause and switching between the hookshot and hammer while the hookshot is extending for the puffs.

**Comment by Nicholas-Steel** [comment]
Isn't Aaarghus the eyeball boss in Misery mire?

**Comment by BlueViper85** [comment]
Arrghus is the Swamp Palace (DW dungeon 2) boss
