### ISSUE TITLE
Idea more Difficulty For v8

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#291]
Submitter: Tantalus-X
have litte idea remove all heart container and make to Heart 68 (17 heart container ) Pieces for more Difficulty.

pls remove from the Boss random pool the Map and Compass and give boss more key items.

**Comment by ChristosOwen** [comment]
We will likely be making safety items (including heart containers/pieces) customisable in the client going forward.

Maps/compasses have strongly been asked to remain, but their functionality may be improved.

Bosses being more weighted to drop items shan't happen (as it takes away from the random element) but their logic is due to be optimised in terms of big/small keys. 

Of the relevant actions here it's already logged and being discussed in #201 so going to close this one.
