### ISSUE TITLE
[v7] Dark palace pre big chest room dark

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#295]
Submitter: MisuStar
[v7]

On playing I stumbled on a completely dark room (the one leadingto the big chest in dark palace.
No light was to be seen, the room was pitch black as long as I didn't use items or the sword (the effects were perfectly fine) but orientation proved difficult anyway.

Data:
Alttp: version: v7
Seed: C0392013
Emulator: Snes9x v1.53
Lantern not found at the time of encounter.

**Comment by BlueViper85** [comment]
In this seed, the lamp was placed in Misery Mire. Palace of Darkness does not include any major items to access Misery Mire, so this fits the expected logic of V7.

There's no contact information so I'll leave this here in case MisuStar sees this:

Randomizer expects, and often requires that you complete dungeons out of order (or even enter one dungeon, get an item, and complete another in potentially rare cases).  The lamp is required to see in the dark rooms in the Dark World, and the lamp will not be placed in a location that requires you to have the lamp to see (there is a known bug with this and Turtle Rock, which will be fixed in the next update though)

So the ideal answer here is to go Misery Mire and beat it (or at least get the lamp) and THEN go and complete Palace of Darkness.

Thanks for the feedback, and hope you continue to enjoy randomizer!

**Comment by Nicholas-Steel** [comment]
On another note, you can use the Ether Medallion or the Ice Rod to freeze the enemies to make them visible landmarks you can use in addition to holding down the Sword button to more easily navigate this area.
