### ISSUE TITLE
[v7] C6641344 Possible Misery Mire Key Lock

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#296]
Submitter: Josh
Hi,

My seed is C6641344.  I believe I have accidentally caused a softlock in Misery Mire.  I have no small keys and do not have the big key.  I ran the spoiler log on my seed to see the locations of the items.  There is a small key locked in the big chest, but I cannot open it due to not having the big key.  Also, in the big hub room, the last small key I used was to open the locked door in the upper-right.  I realized afterwards that I should have used it to open the door in the lower-left instead.  I now have no small keys to open the lower-left lock.  Beyond that door, I believe, is a room with floating stalfos heads, one of which drops a small key, but I cannot access the room.  Additionally, since I can't access that room, I can't get to where the compass would normally be.  The spoiler log tells me that the compass chest has the big key.  Finally, without being able to access the room with the floating stalfos heads, I also cannot reach where the big key would normally be.  The spoiler log tells me that there is another small key in the big key chest.

I am pretty sure that I have opened all other chests in the dungeon and found all other small keys.  I found the map, compass, lamp, the key in the spike room, and the key underneath the skull jar.  I used these two keys to open the lock in the large room where the key is underneath the skull jar and the lock in the upper-right of the big hub room as previously mentioned.  Please let me know if there is a workaround or if I have missed something.

Thank you.

**Comment by BlueViper85** [comment]
What I'm not seeing on the list is the key in the Fish room (northwest of the Big Hub room) with all the spikes and he crystal switch. It's another key under the pot. If I'm reading this properly the only skull pot key that was obtained was the one in the spike room (with the hidden chest).

There is no means of communication on this one. So I'll have to try to get to Misery Mire and check myself or attempt to gauge based on the spoiler log when I can generate it, though I do suspect the fish room will be the missing link here.

**Comment by KatDevsGames** [comment]
Did you check the skull in the northwest corner of the fish room? It's the room if you go to the square spike room and head 2 north and then west.

**Comment by BlueViper85** [comment]
Generated the spoiler log, and evaluated key usage.  While it doesn't sound like the Fish Room key was obtained, it is still possible that even with that key it is still possible to key lock yourself.  There is a key door on the south door of the large fish room, and if you picked up the key from the pot and used it there, there would be no remaining keys.

I've assigned this to Chris for logic updates and Dessy for implementing the logic once it's completed.  It seems like the best solution is that if the Big Chest has a key then the big key can't be in either the Big Key chest or the compass chest OR, similarly, if either the Big Key or the Compass chest has a key, the other can't be the big key (or vice-versa).

Mire log:

**[dungeon-D6-B1] Misery Mire - big chest...................................................Key
[dungeon-D6-B1] Misery Mire - compass.....................................................Big Key
[dungeon-D6-B1] Misery Mire - big key.....................................................Key**
[dungeon-D6-B1] Misery Mire - big hub room................................................Map
[dungeon-D6-B1] Misery Mire - end of bridge...............................................Lamp
[dungeon-D6-B1] Misery Mire - map room....................................................Compass
[dungeon-D6-B1] Misery Mire - spike room..................................................Key
Heart Container (Vitreous)................................................................20 Rupees

**Comment by sporchia** [comment]
In rechecking the logic, this might not be an issue, you need big key to have access to unlock the door in the basement which would be the last key you use, so I don't think there is anyway you can use up all your keys before then, allowing the big chest to always have a small key no matter where the big key is

**Comment by BlueViper85** [comment]
The door in the basement was removed and hasn't yet been added back so you would have an extra key.

There are three small keys and the big key locked behind the lower-left room.  In this instance they are likely not key locked if they get the key in the fish bone room BUT if they were to unlock that door with that key (or if they already did that) THEN there would be a key lock.

**Comment by BlueViper85** [comment]
I should add that if the big key were placed before the big chest had a key then the logic for Misery Mire might actually be fine. This may also be simply a result of that.

I've built a function to check for that and still need to test it further to see if it does apply here among several other places.  This function effectively forces the big key to be placed before the big chest can be filled, allowing the big key Chest logic to be properly evaluated.

**Comment by BlueViper85** [comment]
Here's a diagram I drew up showing an example of key usage that could lead to this lock out (click to enlarge).  It's very crude and coloring is inconsistent, but it still seems to do the job. I labeled the chests with what they have in this seed if it's different than the labeled items.

I'll look into the function I've been testing more later.  

Edit: I forgot to X the door with the Jellyfish Key, so I fixed that and various color issues, and added circles to ensure it was a little more clear what could happen.  Yellow lines show using a key on a yellow-circled door (the order of which can vary, but if you use all of the listed keys in this seed with one of the yellow-circled doors, it doesn't change anything).  The red Xs and circles show keys, doors, and chests that can't be accessed.  The pink line/circles shows the relation of the big key and big key chest that prevent access to one another because the big key is behind two locked doors.
 
![miserymire](https://cloud.githubusercontent.com/assets/12190332/21959296/25f5e4a0-da88-11e6-9e1b-68f1b3c47cbb.png)

Here's the mire chest assignments for this seed again, showing that all the keys that generated in chests are accounted for.

**[dungeon-D6-B1] Misery Mire - big chest...................................................Key
[dungeon-D6-B1] Misery Mire - compass.....................................................Big Key
[dungeon-D6-B1] Misery Mire - big key.....................................................Key**
[dungeon-D6-B1] Misery Mire - big hub room................................................Map
[dungeon-D6-B1] Misery Mire - end of bridge...............................................Lamp
[dungeon-D6-B1] Misery Mire - map room....................................................Compass
[dungeon-D6-B1] Misery Mire - spike room..................................................Key
Heart Container (Vitreous)................................................................20 Rupees

**Comment by sporchia** [comment]
you are right

**Comment by BlueViper85** [comment]
The big chest only checks that you either CanLightTorches OR that the big key isn't in either of those chests, so another step to check for big key and a key placement. If we want to prevent a soft lock here from being possible at all (which I support) then the misery mire key logic should be corrected to account for this situation.

**Comment by ChristosOwen** [comment]
This was fine previously, so yeah it must be the big chest being able to be a small key causing issues.

Honestly I'm now beginning to think that all dungeons should just have simple key logic for Casual. It seems pretty pointless to keep trying to optimise it while accounting for bad decision making, since it doesn't really add all that much and it makes the code really hard to manage/understand. 

I would much rather spend time writing optimised logic accounting for best case scenario decision making in the Speedrunner version.

**Comment by BlueViper85** [comment]
While I do agree that simplified key logic isn't a bad solution, I know you put a lot of effort into the keynlogic and I'd hate to see that go to waste.

This particular case is a significant edge case and otherwise the v7 key logic seems to be doing well.

I do have a solution here that seems to work. Basically if the big key is in the compass chest or big key chest then the big chest isn't accessible until it finds two keys in the more easily accessed locations.

Obviously if you wanted to switch to a simpler means of addresssing keys in future versions I have no problem with that.  Just something worthy of consideration (perhaps a see what happens after v8 and simplify in v9+)

**Comment by BlueViper85** [comment]
A fix for this issue has been applied to the base code and will be available when the next version is released (no ETA).  Closing this issue since a fix has been applied.
