### ISSUE TITLE
Edit "Bottle w/ Gold Bee" Sprite

### ISSUE THREAD

**Issue by churine** [Dessyreqt/alttprandomizer#298]
How terrible.

... okay, I'll take the pedantry award.
Because the item names are no longer shown, there's no way to tell bees apart without releasing them, which are one-time use without the net.

**Comment by BlueViper85** [comment]
Haha award given, I suppose. But honestly this isn't an unreasonable request.

Though with it without the text, since the game is the Japanese version it wouldn't be distinguishable with the text either (for those who can't read Japanese anyway).

I do think there's benefit to this, but I don't know the amount of work it would take to change this so I shall leave this for the more knowledgeable people to comment on.

Knowing that SmallHacker handles the graphics work, I've assigned this to mmxbass as a means of identifying that this isn't meant for Dessy or others, and SmallHacker isn't in the assignee list.

**Comment by Smallhacker** [comment]
The trivial solution would be to change the palette for the regular bee. On the item screen, the best choices would be either shovel handle brown or cape red. With more effort (and giving it two dedicated tiles), one could turn it silvery.

Now, the question is whether to bother updating the "holding item" sprite.

**Comment by Nicholas-Steel** [comment]
It's 3 letters, can't you replace the japanese text with english text?

**Comment by BlueViper85** [comment]
The text was intentionally removed from the item menu since it's not useful in a foreign language and otherwise most items are very distinguishable already.  Adding text back, especially just for one item, would be inconsistent and look out of place.

This is to say nothing of any technical challenges that are presented in changing the Japanese characters to English.

**Comment by Radagast81** [comment]
How about just adding some white pixels/stars around the bee that indicate the "stardust" that golden bees have when they fly around you?

**Comment by Nicholas-Steel** [comment]
Or mirror the graphic?

**Comment by BlueViper85** [comment]
Adding something "sparkly" makes sense, but I can't speak for ease of implementation compared to SmallHacker's idea of just swapping the colors for he regular bee.

Mirroring the image I think isn't a good solution. I thought about that myself, but then it's still a sort of guessing game of which one was mirrored. Obviously you could figure it out fairly easily and know every time after but a change like this should be something more instantly recognizable (IMO anyway)

**Comment by Nicholas-Steel** [comment]
Yeah, I didn't think the mirror idea through very well. If you remove the white glint/reflection from the right side of the bottle graphic you will increase room for sparkles.

(Dunno if hotlinking works)
http://brokenanalog.com/wp-content/uploads/2013/12/Z3_Inventory.png

**Comment by BlueViper85** [comment]
If the sparkles were added, that seems like a good idea, but I'll leave that up to smallhacker or whomever works on the graphic for this.

That menu screenshot is from the GBA version of the game, which had a redesigned item menu, and allowed you to keep the shovel

**Comment by Nicholas-Steel** [comment]
That's what I figured the resolution of all the item graphics was terrible.

**Comment by Nicholas-Steel** [comment]
Replaced the link to the inventory image with a better one.

**Comment by Nicholas-Steel** [comment]
I included mention of this on the dev document for v8: https://docs.google.com/document/d/1rcIpr-1chTGtgmaYY6wyV1DeOoWqBcYF8kXWcpQwFRU/edit

**Comment by Smallhacker** [comment]
We have plenty of free space in VRAM after removing the Japanese inventory font, so we can easily add new tiles. Aside from actually designing the tiles and sending Karkat a new version of the graphics file, switching the good bee to use those tiles is about as simple as changing the palette it uses.

**Comment by churine** [comment]
If there's enough space for simply new tiles
![goodbee](https://cloud.githubusercontent.com/assets/19752470/22535124/28f41bb6-e8f9-11e6-86d2-7818f35bda1b.png)

I wouldn't bother updating the holding item since the only time it shows is when you get it on the inventory anyways, and only from either returned from the fairy pond or a chest
The only issue I could see down the line is if shops are randomized, but the existing bee for sale uses the enemy sprite instead, much like potions use their own

**Comment by ChristosOwen** [comment]
This is implemented in the live web version: http://vt.alttp.run/
