### ISSUE TITLE
Idea for code restructuring

### ISSUE THREAD

**Issue by Radagast81** [Dessyreqt/alttprandomizer#306]
Hi,
I've read some of the feature requests and issues with the glitched randomized seeds and have reviewed some of the code as problems with the distributions accured.

Here what I noticed:
- The 2 Classes RomLocationsCasual and RomLocationsGlitched are mainly the same and only differ in the CanAccess logic
- There were several bugfixes in made in the CanAccess logic of RomLocationsCasual that also should have been made in RomLocationsGlitched
- There has been a feature request to tell which glitches are needed for the glitched seeds
- It's hard to debug the CanAccess logic of RomLocationsGlitched, as it's not easy to decide how a location is supposed to be accessed. (Is the lack of one condition intended (because it's obsolet due to a glitch) or is it a bug - perhaps this is just my opinion as I am only familiar with the minor glitches of the no major glitches run.) 

So this is my suggestion to improve this (only a quick sketch):
- Add an interface:
```
public interface IGlitches
{
    bool FakeFlippers { get; set; }
    bool BombJump { get; set; }
    ...
}
```
- Change the delegate Method Access to:
```
public delegate bool Access(List<InventoryItemType> have, IGlitches allowedGlitches);
```
- Then combine the 2 files RomLocationsCasual and RomLocationsGlitched to one, by merging the CanAccess logic. For example change
```
new Location
{
    Name = "Hobo",
    CanAccess =
        have =>
            have.Contains(InventoryItemType.Flippers),
}
```
to
```
new Location
{
    Name = "Hobo",
    CanAccess =
        (have, allowedGlitches) =>
            have.Contains(InventoryItemType.Flippers)||allowedGlitches.getFakeFlippers(),
}
```

By this the difference between the possible locations of casual and glitched difficulty reduce to flags which glitches are supposed to be known.

Advantages:
- No code repetition over the different difficulties, therefore bugfixes don't need to be shared over all affected files
- It's easier to debug, cause it's easy to detect which glitches are meant to be used to get to the location
- The complexity analysis could be improved to calculate which glitches are required to solve the seed

Drawback:
- The CanAccess equations will get a bit more complex, as they have to contain all alternative access pathes due to the glitches
- Needs some bigger refactoring

Let me know what you think of this. If it suits you I would be happy to help with the implementation...

**Comment by BlueViper85** [comment]
I do have concerns about how manageable the logic becomes if they're merged, but with enough care that may not be an issue.

A few things worth considering:
- If multiple logic paths were combined into one, using some check to skip some of the logic would probably be necessary to ensure the mode-specific logic checks ran at the appropriate time.  Otherwise you'll have the logic for one being evaluated for the other which could have unexpected results.
-If any other modes are added in the future there logic then grows further complex.
-Not all bug fixes for one mode apply to other modes since so many places can be accessed without items that are otherwise necessary, or other dungeons can be accessed by clipping out of others..  I don't know how much this applies, but it's worth considering for this.

**Comment by Radagast81** [comment]
Thank for your feedback! Here my thoughts regarding your feedback:
- Performance
=> I don't think the perfomance will drop through these adjustments as only checks to boolean variables are added and they are practically free 
- If any other modes are added in the future their logic then grows further complex.
=> I don't think that is the case, as the planned modes all are just variations of the glitches that the user should know to be able to complete the seed. (Speedrun-Difficulty should just be a subset of the glitches allowed in the glitched difficulty.) Other variation due to the difficulty don't affect the locations, or at least not the CanAccess logic. (e.g. less heart container, bug net/powder lateGameItems,...)
- Not all bug fixes for one mode apply to other modes
=> Yeah that's right, but e.g the access through clipping is mapped to a glitch-flag. If for example the dungeon can be entered with the cape or through clipping (e.g bumper cave), then the logic looks like
```
have.Contains(InventoryItemType.Cape)||allowedGlitches.getBasicClipping()
```
if you then determine that the logic is not correct for casual seeds cause you also need a glove to lift the rock in front of the cave you can adjust the logic just for this case
```
(CanLiftLightRocks(have)&&have.Contains(InventoryItemType.Cape))||allowedGlitches.getBasicClipping()
```
so that should not really be an issue.
=> Other thing is with the possibility to access many places through clipping (as this is between different dungeons or other possibilities doesn't really matter):
Yeah it really has to be considered, if it is possible to add the logic for clipping so that the logic keeps maintainable. I think it's possible cause the functions are well structured (e.g it's obvious what CanAccessNorthWestDarkWorld represents and regardeless which glitch you used, you can everytime access the complete northwest darkworld and are not limitted to parts of it - or am I wrong?)

**Comment by BlueViper85** [comment]
Just a few responses:

My concerns about the performance stem from two things.  Admittedly both or either could be incorrect, I'm just adding these as thought points if this is implemented.

1. There would have to be additional things added besides adding glitches to the CanAccess for chests.  Keys matter in a different way (most likely leaning towards not mattering as much.  In glitched, the Pegasus Boots are a force item in Link's house since they are useful for several clips.  Using the existing "ForceItems" and even "NeverItems" checks would have to be able to be made more dynamic than they are, otherwise you're still creating two sets of Locations with different rulesets.  At least in my (admittedly novice) experience, any conditions I've put on these aren't accepted.

2. Yesterday I was messing with misery mire and added a check for big keys in four specific chests before the Big Chest could be considered accessible.  This initial implementation practically doubled the ROM generation time (from 5 up to about 9 seconds)  I was admittedly doing a little more than just checking Boolean values since it was also referencing the chest locations each time.  The compound affect of changing each location (since there are many) as well as any potential chest-specific logic changes that require any additional checks than just the glitches could add time over the course of generation.

As for the other modes, if changes to key logic are made from one mode to the other (for example, if speed runner mode were added it could be far less lenient on key placements in favor of randomization, but to the detriment of potential key locks).  This changes the chest logic from one to another.  A fair example is the key lock I talk about in #296 ) It's rare, and speed runners wouldn't be likely to cause it, but casual would.

Your other comments all make sense with your explanation, at least with my limited understanding of where the various glitches can provide access to.

Again, just to be clear here, I'm not trying to shoot down the idea.  I think this could certainly work.  But there are situations to be considered of for the implementation if it happens.

**Comment by Radagast81** [comment]
Again thanks for your response. I fully understand your concerns and that kind of feedback is absolutely what I hoped for, so I can more critically reflect my idea to see if there are show stoppers or other critical problems.
- Add 1)
I absolutely agree that you want to make the "ForceItems" and "NeverItems" checks dynamic dpendent on the difficulty. There some solutions, first is: Override the property in the Location-List after the reset, second is: Mark these properties also as delegate methods and return the desired value dependent on the difficulty or also on the allowed glitches.
- Add 2)
Yeah it is easy to affect the performance considerably, but the worst case with the glitches will be something like 
```
allowedGlitches.getBasicClipping()?<Glitched-Check>:<Casual-Check>
```
this is the same as
```
if allowedGlitches.getBasicClipping() {
   return <Glitched-Check>;
else
   return <Casual-Check>;
}
```
The if-Statement here is practically free and then you have the same equations afterwards as today, so the performance should stay the same.
So in the cases where the checks for glitched and casual differ considerably you could still perform seperate calculations for the different leafs, but you also have the possibility to harmonize the checks over the difficulties...

- Keylocks:
I don't think you want keylocks in a speed runners difficulty, there could be some situation where you feel forced to decide between one way or another and one of them leads to a keylock. Then in as speed runner it is fatal cause you most likely have no save file and therefore have to restart the seed...

**Comment by Dessyreqt** [comment]
Implementing your suggestions would make the code significantly harder to maintain, especially as we add more difficulties. The RomLocations files should be viewed more as data files that happen to be expressed as code. Thus there will definitely be a certain amount of repetition. However, it also allows for things such as being able to exclude locations for certain difficulties.

Common logic already exists in the BaseRomLocations class. 

> There were several bugfixes in made in the CanAccess logic of RomLocationsCasual that also should have been made in RomLocationsGlitched

What are you speaking of, exactly?

I agree there is still refactoring that needs to be done, but merging the locations files is not the way to go.

**Comment by ChristosOwen** [comment]
I agree with Dessy here that merging Casual with Glitched is not a good idea.

Breaking down each location in Glitched to account for the combination of glitches which allow you to reach each location is a significant amount of work, with very little return? It's not as simple as you suggested, I think. For example to illustrate how complex this would get, let's consider trying to get to one of the 4 chests in the Hookshot Cave in East DM:

Step 1: Reach the portal on West DM. This requires Flute or Gloves/Mitts or a simple DMA clip.

Step 2: Reach DW East DM. If you have the Moon Pearl this only requires an upper clip. If you don't have the Moon Pearl then you would need a Bottle to YBA. This allows you to gain Super Bunny status which in turn allows you gain Link status in the DW without the Moon Pearl. You can then either do another YBA to 1 if you have a second bottle or do DW DMA to reach the mountain again. You would then need to correct the camera since it works differently than in the LW, but you can't leave the Overworld since you would lose Link status. You can then do the same upper clip we would have done had we had the Moon Pearl initially.

Alternatively to the above, if we have the Mitts in addition to the Moon Pearl, we can use the East DM portals right off the bat. To get over here we would also need (Mirror and Hammer) or Hookshot or a simple clip.

Step 3: Now we need to get access to the cave. We need either Gloves/Mitts to lift the rock and to be Link in DW so either need the Moon Pearl or to have performed the steps outlined above. Alternatively we need the Mirror to perform a screen scroll without requiring Gloves/Mitts. 

Step 4: Once inside, we need the Hookshot to reach the chests and also Bombs if we entered the cave from behind.

Writing logic for every location like this would be a huge pain. Furthermore in dungeons the key logic would also then have to be considered, for example if we chose Turtle Rock as an example, the logic is almost identical to the above, but then we can also enter Turtle Rock from the main entrance, the upper clip or the lower clip. These require different items. Then depending on key logic, we might not be able to reach, for example the Crystaroller Room chest, from the lower clip or upper clip, so would be forced to enter through the front door. It's just so complex to try and do this...

As far as I can tell there haven't been any logic issues with Glitched as yet.

**Comment by ChristosOwen** [comment]
As for speedrunner difficulty, there will be keylocks possible but you will never be forced to gamble between one path or another. It's a simple case of the player always knowing which door gives them the most chests by opening it, i.e. best case scenario logic opposed to worst case scenario which is used in Casual.

Players will know this going into it and it allows much better optimisation of items/keys. It's also FAR simpler to write because we don't have to keep considering "Players can choose door A which then means this, or door B which then means this, etc" but can simply say "players will choose door B".

Hope this makes sense.

Also the minor glitches in Speedrunner will barely change the logic from Casual except in a few cases.

**Comment by ChristosOwen** [comment]
Once everything is done for all 3 versions, Casual is going to have by far the most complex code within dungeons since we have to consider multiple choices for every key. Writing/maintaining/understanding Speedrunner and Glitched should be far easier I think.

I also don't think the code should be equivalent to an exact outline of how to reach a location in Glitched. That's what the other resources/asking people etc is for.

**Comment by Radagast81** [comment]
Thanks for your feedback! This seems to be a real problem and also it has still some benefits, I absolutly underestimated the logic variations that are possible in the glitched cenario.
And that my wish or suggestion the location accessible logic could reflect possibilities to enter that location is utopian.
Thanks for your detailed explanations and keep up with the great work!

P.S.:
As with the buggs that are shared between casual and glitched difficulties, i had the key logic in tower of hera in mind, where in casual the loactions have been fixed to work with the distribution as the glitched has been unmodified. I was unsure if this is related to glitches or should have been adapted in both versions and it's more a feeling that there are more similar issues.
You must see that the audience for glitched seeds is very limited and that it's very unlikely to get bug reports for those seeds (i think the percentage for glitched seeds is < 1% compared to casual seeds, so for any 100 issues regarding casual seeds there is only 1 issue to expect for glitched seeds). So that there are no issues for glitched seeds seems to be normal for me, even if there are bugs left (which hopefully is not the case). I just hoped for a greater synergy between the difficulties...
