### ISSUE TITLE
[v7] C1521781 - Complexity 2. Seed unable to be completed due to Moldorm / Big Key issue

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#309]
Submitter: InexpensiveGamer
[v7]

Requires glitch to get necessary items (fire rod, moon pearl) on Eastern Death Mountain. Completexity 2 Path shows get hammer from Sahasrahla but Green pendant is in Tower of Hera that needs fire to start. Lantern in Misery Mire.

**Comment by BlueViper85** [comment]
No seed number included, so the "completability" cannot be validated.  Hookshot can also provide access to Eastern side of Death Mountain and Hookshot location isn't specified.

No direct contact information was provided so I am closing this issue; however, if you see this issue it can be reopened.  Just comment with the Seed number and I (among others) will be alerted to the comment and it can be evaluated and re-opened at that time.

**Comment by KatDevsGames** [comment]
This guy I believe is reachable on twitch? 

On January 20, 2017 11:49:16 PM EST, BlueViper85 <notifications@github.com> wrote:
>No seed number included, so the "completability" cannot be validated. 
>Hookshot can also provide access to Eastern side of Death Mountain and
>Hookshot location isn't specified.
>
>No direct contact information was provided so I am closing this issue;
>however, if you see this issue it can be reopened.  Just comment with
>the Seed number and I (among others) will be alerted to the comment and
>it can be evaluated and re-opened at that time.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Dessyreqt/alttprandomizer/issues/309#issuecomment-274235518

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by BlueViper85** [comment]
It appears you are correct.  I found a VoD and found a part where he was typing up this issue.  Fortuantely he already had the emulator open from another run, so when this Seed was opened it showed the fie name on stream with the seed number.  The seed was C1521781.

Link to the VoD where it shows the Seed Number on start up.

Hookshot is at Catfish.

The Big Key was on the first floor.  This issue seems to relate to the logic issues already identified where Moldorm is considered beatable without getting the big key Per issue #266 

I'll leave this closed since it's being addressed in the other issue.
