### ISSUE TITLE
[v7] Unaccessable chest

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#313]
Submitter: Devan
[v7]

If you beat Agahnim (Light World), you won't be able to access the chest that would normally contain the magic cape. This is especially harsh to those that don't have the titan's mitt.

**Comment by BlueViper85** [comment]
The chest with the magic cape is accessible whether you have beaten agahnim 1 or not.

You need the mirror to access it either way, but if you don't have the mirror you should be able to Save and Quit to return to the Light World if you need to go back.

You may need to the hook shot to get there from the pyramid or you might need to warp to the dark world from the town afterwards to get there if you don't have the hook shot, but it's perfectly accessible either way.

In fact you don't need the titan's mitts either since there is a bush you can destroy that gives you access to that small area to mirror.

If you see this and can provide additional reasoning for why this may be inaccessible just add a comment and we can reopen if necessary.
