### ISSUE TITLE
Feature: Option to toggle boss behaviour changes

### ISSUE THREAD

**Issue by Nicholas-Steel** [Dessyreqt/alttprandomizer#316]
I feel like we're starting to move towards changes that have a dramatic effect on the core gameplay with the tweaks and changes that are slowly being applied to various bosses in the game like Aghanim, Ganon, Koldstare etc.

It would be nice, from a casual perspective, to have an option to retain the original boss behaviours.

**Comment by ChristosOwen** [comment]
Kholdstare hasn't been changed; only Agahnim (1 and 2) and Ganon have been changed to remove the blue balls and warps, respectively. All other bosses remain unchanged.

I don't really understand why you'd want to re-add either of those. You're simply adding back in the (potential for) waiting time in each fight, which seems dumb to me. It's not like it adds back in any difficulty or excitement to the fights. It's also possible to have no blue balls and no warps in the original game; that's still original boss behaviour which could happen. The only difference now is that it happens every time.

If you want original boss behaviour then ultimately you should go play the original - that sounds harsh but I mean it in the politest way possible.

**Comment by churine** [comment]
Or, if you _really_ want to have Agahnim fire blue balls:
0f56ef (1ed6ef) -> 2271ba0d2901d00aa90199a00da92099f00d over the nop'd (ea) section
And for Ganon warps:
0e91e3 (1d91e3) -> 2271ba0d2901 over the a900eaeaeaea

if all that doesn't make sense to you I ended up making a simple patch for it, since it's a really trivial thing and people want it so I guess sure why not
[rng.zip](https://github.com/Dessyreqt/alttprandomizer/files/742907/rng.zip)

**Comment by Nicholas-Steel** [comment]
Neat zilarch, thanks.

**Comment by Nicholas-Steel** [comment]
The original boss behaviours have been re-instated, which is awesome and quite unexpected. Thank you, developers.
