### ISSUE TITLE
[v7] Softlock, or ignorance on my part?

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#318]
Submitter: Bob Locke
[v7]

A Link to the Past Randomizer Log
---------------------------------
Version: 7
Creation Date: 1/29/2017 12:34:44 PM
Complexity: 7
Seed: C2494735

Complexity Analysis
-------------------
Step 1 - Items reachable from start:
  [cave-022-B1] Thief's hut [top chest].....................................................Magic Mirror
  [cave-022-B1] Thief's hut [top left chest]................................................Bottle (Blue Potion)
  [cave-035] Sahasrahla's Hut [right chest].................................................Bottle (Bee)
  [cave-050] cave southwest of Lake Hylia - generous guy....................................Hookshot
  [cave-050] cave southwest of Lake Hylia [bottom right chest]..............................Shovel
  [dungeon-C-1F] Sanctuary..................................................................Hammer
  [dungeon-C-B1] Hyrule Castle - boomerang room.............................................Flippers
  Piece of Heart (Maze Race)................................................................Quake
  Piece of Heart (Thieves' Forest Hideout)..................................................Cape

Step 2 - Items reachable after collecting all items from Step 1:
  Hobo......................................................................................Mushroom
  King Zora.................................................................................Lamp
  Piece of Heart (Pyramid)..................................................................Red Boomerang
  Sick Kid..................................................................................Ocarina

How am I supposed to get to the Dark World Pyramid with these items? I can only guess that's what Piece of Heart (Pyramid) means. I've exhausted all my options, every Dark World portal requires a Glove to access, except Death Mountain. This is a glitchless seed, so it shouldn't be expecting me to glitch my way off of Death Mountain, right?

Also is there a listing or map of where these cave locations are? "[cave-062] C-shaped house" is a mystery to me and tells me nothing about where it is. Is this in the Dark World?

Sorry if I'm wasting your time.

**Comment by BlueViper85** [comment]
You would use the Cape you get from the Thieve's Hideout to enter Agahnim's Tower and run through there and beat agahnim to gain access to the Pyramid. You can get the red boomerang that way, but keep in mind you need the Moon Pearl to do anything otherwise meaningful in the Dark World, which I don't see specified here.

As for the maps, there is an extensive map list at a link at the bottom of the Randomizer download page. I'll paste the link here as well. Caves are numbered to math the cave listings on this page.

http://ian-albert.com/games/legend_of_zelda_a_link_to_the_past_maps/

There is no contact information provided so I'll leave this here. If you see this and have any questions, you can still comment. Should an issue be identified after that time this can be reopened to track that issue.
