### ISSUE TITLE
Version 8 idea

### ISSUE THREAD

**Issue by Joki81** [Dessyreqt/alttprandomizer#324]
In the next version, could you please randomise all the caves and dungeon entrances? Perhaps with exception of the castle at the start of the game.

And how about randomising the bosses? i.e. Helmasaur King in Desert palace?

**Comment by ChristosOwen** [comment]
A door/entrance randomizer would be a separate project. And it's extremely considerable work due to how the game works and would require its own logic. This may happen in the future though but not as part of the item randomizer.

Randomizing bosses would just be frustrating when you go through a dungeon only to realise you can't kill the boss because you're missing an item which the dungeon didn't require but the boss does require. So no plans to do this.
