### ISSUE TITLE
Increase Cap Limits of Stats (997 for screen transitions, 99 for bonks etc)

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#325]
Submitter: Wizzrobe
[v7]

While watching casual randomizer streams, I've noticed that the screen transition number does not seem to go past 997. 

After confirming this was not meant to be the cap, I decided to report it.

**Comment by Smallhacker** [comment]
After looking into the code and talking to Karkat about it, I've determined that it's caused by two separate bugs:

1. The code that increases the counter accidentally stops right before reaching 999 (instead of 1000), making it max out at 998.
2. The code that finalizes the stats before the credits subtracts one from the counter to remove the GTower duck transition, whether or not it has already capped out. As such, the maximum becomes 997.

My suggested solution is to change the first piece of code to cap out at 1000 (not 999) as it'll be decreased to 999 by the finalization code. Even if it somehow ends up too high, my credits code still caps the displayed value at 999 anyway.

(As a side note, Karkat is also considering increasing it to a four-digit number, in which case it should be capped at 10000.)

**Comment by Nicholas-Steel** [comment]
Or you could have the subtraction code check if the transition counter is capped and just... not execute if it is capped.

**Comment by Smallhacker** [comment]
Storing an extra bit of information elsewhere to tell 999 (uncapped) apart from 999 (capped) is literally several times more complex than capping at 1000 and always subtracting by one.

**Comment by ChristosOwen** [comment]
We have this logged on our end now too, and this will also happen... eventually. No need for the duplicate issue here!
