### ISSUE TITLE
Purple Chest Disapears When The Player Has All Bottles

### ISSUE THREAD

**Issue by XModxGodX** [Dessyreqt/alttprandomizer#329]
In seed C4294552 I needed the bombos medallion to access both medallion dungeons but it was in the purple chest but by the time I got there I had all the bottles which seems to make the chest disappear.

**Comment by BlueViper85** [comment]
This is rather unusual, and I will say that I have had 4 bottles and still been able to collect the purple chest in the past so I'm hesitant to say this would be exclusively tied to the bottles.

Since it wasn't stated, I should ask: did you take the frog in the Dark World back to the blacksmith's house in the Light World? That is a requirement before the purple chest is available.

**Comment by XModxGodX** [comment]
Whoops I didn't think that would matter since I got the level 4 sword and purposely ignored it just in case it would downgrade my sword. Sure enough it showed up after returning him to the blacksmith.

**Comment by BlueViper85** [comment]
Awesome!  Fortunately downgrades are prevented, but you can always drop off the frog without giving the sword as well. I'll go ahead and close this then. Let us know if you have any more problems/questions/concerns!
