### ISSUE TITLE
C0001337- FireRod issue

### ISSUE THREAD

**Issue by munsta0** [Dessyreqt/alttprandomizer#330]
Complexity Analysis is missing the 3rd and 7th crystal.

The Firerod is in the big chest of the skull wood and the big key is in the 2nd part of the dungeon, where we are required to have the firerod to access.

Seems impossible to me on a casual standpoint.

**Comment by BlueViper85** [comment]
The complexity analysis failerd to complete the item collection because of the firerod/big key issue you mentioned.

This issue results from an issue with the way the randomizer checks for the big key before placing items in the big chest.

This has been fixed in the base code and will be part of the next randomizer version when it's been completed (no ETA right now, though)

Thanks for the report, let us know if you come across anything else!

**Comment by munsta0** [comment]
Alright, thanks for the heads up. I guess I'll have to check analysis on my next seed to make sure it's valid!
