### ISSUE TITLE
V8?

### ISSUE THREAD

**Issue by thejoshwolfe** [Dessyreqt/alttprandomizer#335]
Is this C# client planning to support V8? It looks like there's a different project that is continuing development as a webapp. Are there plans to keep this C# client up to date, or is the webapp the way of the future?

**Comment by SmashManiac** [comment]
I believe this is the webapp being referenced: http://vt.alttp.run/

I'm noticing it has more features than V7, but I don't know if they are unreleased V8 features or independent work.

Personally I prefer using desktop apps because you can back them up and use them offline, but it looks like the [upcoming ALttP Randomizer tournament](http://alttp.challonge.com/rando2017) will use the webapp, although I'm not exactly sure why,

**Comment by Lebon14** [comment]
The WebApp is VERSION 8, the one is currently devlopped. The downloadable client is VERSION 7. Of course, there will new logic, new randomization and stuff in version 8. However, I heard that, at one point, when the webapp will move the VERSION 9, the downloadable software will update to version 8. However, anybody serious about aLttP rando will use the latest logic. So, somebody will create the seed than distribute the resulting rom file to participants to avoid browser-related issues.

**Comment by sectokia** [comment]
Then where does one go to see the source code for the logic being used by the webapp? Specifically whatever the v8 equivalent of RomLocationsCasual is.

**Comment by ChristosOwen** [comment]
This is the GitHub for the live version: https://github.com/sporchia/alttp_vt_randomizer

Specifically what you're looking for is contained within: https://github.com/sporchia/alttp_vt_randomizer/tree/master/app/Region 

You can join the community on Discord to keep in the loop: https://discord.gg/xzxy2Mq
