### ISSUE TITLE
Found a softlock on v7 seed: C4136661

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#342]
Submitter: James
[v7]

The hammer is in the digging game (dark world), and the mirror is in this last "light world" dungeon.
Basically, because of this. There's no way to continue.Complexity was 8.
Need the mirror to do any glitches to even pass this, ha.

**Comment by BlueViper85** [comment]
Hookshot is in Link's house.
Power gloves are accessible
Moon pearl accessible
Cape is accessible

Use the cape to access Agahnim's Tower and defeat him to get access to the dark world.  Follow the path from the pyramid east one screen, then follow it north until you see a small break in the edge of the ground (next to the river) and use the hookshot to fly across.  You won't necessarily see what it hooks onto at first, but I assure you there is something there.

No contact or otherwise identifiable information provided, closing this issue.
