### ISSUE TITLE
Magic Mirror in Purple Chest?

### ISSUE THREAD

**Issue by jalsonmi** [Dessyreqt/alttprandomizer#381]
I was playing a seed with no major glitches and could not for the life of me find either the Bow or the Magic Mirror, and had gotten to the point where I needed one or the other to proceed. I looked at the psoilers and it said the Magic Mirror was in the Purple Chest.

How do you open (or even spawn) the Purple Chest without already having the Magic Mirror? I think this is a bug but maybe I'm missing something.
[ALttP - VT_no-glitches-25_normal-standard-ganon_777641683.txt](https://github.com/Dessyreqt/alttprandomizer/files/1220658/ALttP.-.VT_no-glitches-25_normal-standard-ganon_777641683.txt)

**Comment by BlueViper85** [comment]
This bug report page is for the old randomizer. New issues for the new randomizer should be submitted via the Report an Issue (or similar) button at http://vt.alttp.run


With that in mind, most likely you would get the purple chest and ace and quit which takes you to back the light world since you don't have the mirror.  From there you can take it to the locksmith.
