### ISSUE TITLE
No lamp or duck death mountain

### ISSUE THREAD

**Issue by LexamusPrime** [Dessyreqt/alttprandomizer#385]
I'm in the light world with no lamp or duck and the only place left I can go is death mountain. How do I do it?

**Comment by Arrahed** [comment]
I encountered a related problem. The description page says that no lamp is needed to see in the dark while in the light world. That is not the case for me. All dark areas in the light world (Castle escape, Eastern Palace, Death mountain caves) are black without having the lamp.

I can work around that by blindly navigating the caves/rooms but it looks like a bug to me.
If the bug is version specific, I use 'Zelda no Densetsu - Kamigami no Triforce (Japan).sfc'.
I can do 'fake flipper' so I am pretty sure it is version 1.0.

EDIT: I am using the emulator ZNESW

**Comment by miketrethewey** [comment]
ZSNES is not officially supported by the project.
It sounds like you may also be using a different version of this project.
This page is for version 7's standalone Windows-based application.
Version 8's web-based version can be found via the "Report Issue" Link at http://vt.alttp.run/

**Comment by blackknight36** [comment]
Having the same issue with version 7.  I've tried going through Death Mountain and the first castle but I'm unable to see anything due to the screen being pitch black.

**Comment by blackknight36** [comment]
Also having the same issue with version 8.  Using an identical seed with identical options results in a ROM with the same md5sum as shown below.

```
MD5 (ALttP - VT_no-glitches-26_normal-standard-ganon_597414213.sfc) = ae9af3b327e405c5f648e0eaa6e5ce7e
MD5 (ALttP - VT_no-glitches-26_normal-standard-ganon_597414213.sfc.old.sfc) = ae9af3b327e405c5f648e0eaa6e5ce7e
```

Any dark areas such as the rooms in the Eastern Palace or Death Mountain are impassable due to this.

**Comment by BlueViper85** [comment]
In v7 the light world does not require the lamp. In v8 it does. V7 is no longer being updated. If you have issues with the v8 randomizer please report the issue to the appropriate  “Report Issue” link on the v8 site at http://vt.alttp.run
