### ISSUE TITLE
unable to reach big chest in Thieve's Hideout

### ISSUE THREAD

**Issue by hubenjm** [Dessyreqt/alttprandomizer#395]
I forgot which seed I used, but I've gotten though the entire dungeon of Thieve's Hideout (Gargoyle's Domain) in the dark world except that I could not get into the room containing the big chest, which is locked behind a small key door.

However, my particular seed replaced the chest in the prison where you find the girl, which usually contains a small key, with a different item.

So I'm wondering if it's possible that the big chest actually contains the last small key in the dungeon, which would mean that I could never reach it. And if so, is this intended?

**Comment by ChristosOwen** [comment]
Hello!

You appear to have reported on the outdated GitHub. This one is for the old .exe application (v7 and before).

Be sure to join the community on Discord: https://discord.gg/xzxy2Mq
The new relevant GitHub: https://github.com/sporchia/alttp_vt_randomizer
The current randomizer: http://vt.alttp.run/

In answer to your question, yes, the Big Chest is able to contain the small key (so it can be locked behind the small key door). This was intentional as of v28. Similarly the big chests of Skull Woods and Swamp Palace can contain the big keys (since there are no big key doors to get to the boss), and small keys can be locked behind small key doors in some other dungeons too (POD, Hera, GT, etc although these generally depend on how you use your keys). You can never softlock or key lock however, just sometimes you might not be able to get to some (useless) locations!

**Comment by hubenjm** [comment]
@ChristosOwen Thanks a lot for the clarification! Also really enjoyed your race at GDQ!
