### ISSUE TITLE
STUCK about lamp!

### ISSUE THREAD

**Issue by 1000fruit4nana** [Dessyreqt/alttprandomizer#398]
hi this is my first run through, seed 580480466 on easy mode.

I can't seem to get the lamp and can't progress anymore without light! I went to spoiler log after searching everywhere, and it says the old man has it, but I have already been to him and he just refills my health and won't start the quest, he just stands there. Is this a bug? Do I need the lamp to do the old man quest?
 Alternately I could use the fire rod but it's in the checkerboard cave and I have no mirror yet and can't get it. where I also can't go without a lamp as I am noob a bit. Any suggestions or should I start a new seed?

**Comment by daftinquisitor** [comment]
You're likely going to have to look up maps to navigate the areas that you can't see without the lamp, I ran into the same problem in a few spots. When the old man gives you an item, it's when you escort him to his home cave, the only thing he does after that is refill your health. So if he didn't give it to you already, he doesn't have it.

If you're fairly new to Link To The Past (which your post seems to say you are), you probably shouldn't be starting on a randomizer run, this is more for people who are much more familiar with the game to give it an extra challenge.

**Comment by linktothetrash** [comment]
@1000fruit4nana yeah why are you even asking for help? Shouldn't you already know you're an idiot? this domain is for true Zelda players! get out fucking poseur!

**Comment by daftinquisitor** [comment]
@linktothetrash That's not what I was saying, don't be a jerk. I just meant, since the OP said he's somewhat new to the game, it might be better to start with the original until you're much more familiar with it.

**Comment by linktothetrash** [comment]
@daftinquisitor oh sorry man I'm just trying to get your back cuz like i know how it can be when people don't know stuff and its just really annoying that they dont know stuff, and then other people just ask like questions that they should be able to understand right? @1000fruit4nana maybe be a lil more appreciative, give respect = get respect 
“Life is 10% what happens to us and 90% how we react to it.”

**Comment by ChristosOwen** [comment]
Hi,

On Easy mode there are 3 lamps. Checking the spoiler shows the other 2 are:

Ice Palace - Spike Room | Lamp
Ganon's Tower - Bob's Chest | Lamp

Unfortunately it's not guaranteed that all lamps are not locked behind dark rooms, but at least 1 lamp will always be accessible without going through any dark rooms. This is being fixed in the next release so all 3 lamps are always before any dark rooms. Once you find one lamp the other 2 will then change into rupees, so you'll only actually ever collect one, but it's 3x as likely for you to find one. This is only true for Easy difficulty.

Anyway with the seed in question, you have the necessary tools to get the one from Ice Palace :)

Regarding the Old Man, you have to "rescue" him from the cave to the left of the one you're checking. It's in the dark, so you actually do need the Lamp for that yes. However he already exists in the cave you return him to anyway (weird game huh) even if you haven't yet rescued him!

BTW you posted on a legacy Github. The new one for the current randomizer is:

https://github.com/sporchia/alttp_vt_randomizer

And make sure you're generating seeds from the website not the outdated application:

http://vt.alttp.run/randomizer

Lastly you can join the community on Discord too:

discord.gg/alttprandomizer
