### ISSUE TITLE
[v5] Zelda Follower Fix

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#78]
Submitter: ChristosOwen
Email: ChristosOwen@hotmail.co.uk
[v5]

If you get cape in escape and defeat Agahnim with Zelda following you then you can no longer return her to sanctuary so she is stuck following you. There are ways to end this (collecting master sword, speaking to kiki, obtaining a crystal) but depending on the item distribution you may not be able to do any of these.

Solution: Remove zelda as a follower after defeating Agahnim.

**Comment by churine** [comment]
From what I can see, Zelda prevents: Digging Game, Follower Chest, Lost Old Man, Dwarven Smith.
Kiki's only requeriment is the Moon Pearl, due to the castle gate.
Digging Game, Follower Chest and Dwarven Smith are meaningless, since you need the Moon Pearl for them too.

The only issue is if the Old Man has the Moon Pearl.

So another solution may be to simply forbid the Old Man from having the Moon Pearl [+if the Cape is at the escape] [+you need it to get the pendants]

On the other hand, this also deppends on how much you consider this scenario "glitchless"...

**Comment by KatDevsGames** [comment]
The simple solution is for defeating agahnim to despawn followers. Limiting spawn patterns is not desirable.

**Comment by KatDevsGames** [comment]
Fixed in trunk rom.
