### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by jaysee87** [Dessyreqt/alttprandomizer#83]
<edit 8/24/16 to youtube links> https://www.youtube.com/watch?v=tj5cWImt-jE (v5)  + https://www.youtube.com/watch?v=yIl_PW5W3YQ (v6)
Not sure if this is a randomizer issue or an issue with my sd2snes or console. Console is on a desk with nothing bumping it at the time of the crash.

**Comment by BlueViper85** [comment]
I couldn't tell from the Past Broadcast. Did you try dashing or pressing select to see if there was any audio feedback to indicate if the game actually stopped responding vs just having the video go completely black?

**Comment by jaysee87** [comment]
I tried to S+Q eventually with no feedback. I was able to just hard reset and still had an older save file

**Comment by BlueViper85** [comment]
Obviously you were dashing in the video, were you trying to switch items or do anything else at the time of the crash or was it just while moving and dashing?

**Comment by jaysee87** [comment]
I don't think I was trying to change items at where it crashed. I might have. I was going to a few seconds after that for mirror. Would you like a longer highlight? I was sitting there a while trying to decide to quit the race or reset and see how far back I was sent.

**Comment by BlueViper85** [comment]
I'm watching the whole VoD right now for anything else that might stand out as unusual or unexpected.  Failing that, I've got the Seed and will have some spare time in the next day or so to run through this following your path as well to see how easily re-created this may be.

**Comment by BlueViper85** [comment]
Admittedly I was doing other things while watching the video, but nothing stood out as unusual.  I didn't realize that was a controller input on screen, clearly nothing was pressed beyond the A button.

The only thing that seemed too out of the ordinary was opening like 7 chests in the chest game.  If that somehow played a part that should be fixed in the next release.  But that's pretty much just speculation on my part.

I'll go through and see if I can recreate this tomorrow at all, trying my best to follow your steps if I can't with pre-existing saves.

**Comment by ChristosOwen** [comment]
Opening multiple chests in the chest game has game breaking side effects, but shouldn't be anything to do with this. No idea!

**Comment by BlueViper85** [comment]
I was unable to properly follow through the steps of this one previously, I am currently running through this now to see what I can find.  Even if it doesn't crash it'll be good to confirm.

**Comment by BlueViper85** [comment]
Tracing your steps from beginning to crash did not result in any crashes for me on SNES 9x 1.53.  Admittedly I had two overworld game over deaths that you did not, otherwise I recreated your steps, item/chest order, game overs and fairies, even mirror spots as closely as I could manage.

This seems to be either console or SD2SNES related.  If it was ROM related it was extremely specific.

**Comment by ChristosOwen** [comment]
Nobody has been able to replicate this so closing, as can't fix something we can't do again! If it happenes again let us know though. For what its worth, this kind of crash has happened to me a few times and has been because of my cart/console.
