### ISSUE TITLE
[v6] C9645286, unbeatable

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#88]
Submitter: Malu
Doing my first run in v6 I got this

[dungeon-D1-1F] Dark Palace - spike statue room...........................................Magic Mirror (Can't proceed. Left path led to a chest with the Big Key, right path ends up at a room with two green and one red mimic guy, middle path--small key door)
[dungeon-L3-4F] Tower of Hera - 4F [small chest]..........................................Bow (Can't get to the dungeon without mirror or hookshot)
Ether.....................................................................................Titan's Mitt (Same as above pretty much)
[dungeon-D2-B1] Swamp Palace - big key room...............................................Hookshot (Can't enter without mirror to flood the first room)

**Comment by greenham** [comment]
As far as I can tell, this is indeed unbeatable. If PoD had at least 3 accessible small keys before the spike statue room chest, it would be fine, since you'd be able to reach the mirror. But the BK being in the 'shooter room' chest makes this impossible.

**Comment by ChristosOwen** [comment]
This is indeed unbeatable. 

Dessy - the issue here is Palace of Darkness, specifically the lack of a couple of functions.

First we need "'shooter room' is a small key" and this function needs to be added to all chests within the dungeon, except "shooter room". If the function is 'no' then "Bow" needs to be added to the logic for all those other chests. However "jump room [right chest]" and "statue push room" can be excluded since these already have "Bow" in their logic.

Then we also need "'jump room [right chest]' and 'statue push room' are not keys" and this needs to be added to all remaining chests within the dungeon, excluding "shooter room", "jump room [right chest]" and "statue push room". If it is 'no' AND the above "shooter room is a small key" is also a 'no' then "Bow and Hammer" need to be added to the logic for all of those other chests.

This should allow optimal key and item distribution in this dungeon.

**Comment by ChristosOwen** [comment]
Closing as summarised all of PoD in one report; #123
