### ISSUE TITLE
[v6] Seed: C1852772 Ocarina early bug?

### ISSUE THREAD

**Issue by NagolStrache** [Dessyreqt/alttprandomizer#93]
Nothing game breaking here, just that I somehow got the ocarina much earlier than the game wanted. After looting Kakariko and getting the book, a bottle, the red shield, mushroom and the shovel, I went south to check out the library and the flute boy. After watching the flute boy disappear, I went into my inventory to switch to the shovel. That is when I noticed the "Y" next to the shovel and toggled to the ocarina I never obtained.

Again nothing bad about this bug, but it is kinda funny that the game wanted me to wait until reaching [cave-056] Dark World Death Mountain - cave under boulder [top right chest] in order to actually get the ocarina.
Edit:
Found out 2 seconds after posting that using the ocarina summons the bird even though I haven't activated it at kakariko yet.

**Comment by KatDevsGames** [comment]
You don't happen to have a VOD of this, do you? 

On August 18, 2016 12:31:10 PM EDT, NagolStrache notifications@github.com wrote:

> Nothing game breaking here, just that I somehow got the ocarina much
> earlier than the game wanted. After looting Kakariko and getting the
> book, a bottle, the red shield, mushroom and the shovel, I went south
> to check out the library and the flute boy. After watching the flute
> boy disappear, I went into my inventory to switch to the shovel. That
> is when I noticed the "Y" next to the shovel and toggled to the ocarina
> I never obtained.
> 
> Again nothing bad about this bug, but it is kinda funny that the game
> wanted me to wait until reaching [cave-056] Dark World Death Mountain -
> cave under boulder [top right chest] in order to actually get the
> ocarina.
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/93

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by NagolStrache** [comment]
I created a second file and retraced my steps, here's the video with the bug in action and the spoiler log.

[[V6]Video&Log.zip](https://github.com/Dessyreqt/alttprandomizer/files/425968/V6.Video.Log.zip)
[ALttP Random - C1852772.sfc.spoilers.txt](https://github.com/Dessyreqt/alttprandomizer/files/425969/ALttP.Random.-.C1852772.sfc.spoilers.txt)

Sorry for the bad quality and no sound, had to compress it quite a bit to get it under 10Mb

**Comment by BlueViper85** [comment]
I attempted to recreate this, but could not.  I tested both by just getting the shovel and heading to the flute boy, then going to the flute boy first, and then by following your steps in the video to a T. None of these provided me the Ocarina or the ability to switch between the two.  I'm testing a little further but expect the same results.

While doing so, I noticed that your video didn't show you going to the Flute Boy at all.  For clarity's sake (since you mentioned noticing this after watching him disappear), can you confirm whether or not you visited him prior to the recording? The sanctuary is open, so I assume not, but wanted to be completely sure.

After completing additional testing to ensure I was following your steps completely I was still unable to reproduce.

Were you playing on an emulator or SD2SNES?  If emulator, can you specify which emulator and version?

**Comment by NagolStrache** [comment]
On my first file I encountered whatever this is after getting the shovel and the rest of the items I mentioned before, but didn't notice that I had the ocarina until after the flute boy disappeared and went to select the shovel from my inventory. I created a second file, which is the one seen in the video, and didn't go to the flute boy like on my first file. It doesn't seem like the flute boy has much to do with the bug, as I was able to switch to the ocarina without going to visit him.

I use the ZSnes emulator, and the version I have is version 1.51.

**Comment by BlueViper85** [comment]
Potentially could be emulator-related?  I'll see about testing with ZSnes 1.51 to confirm, as this is a fairly quick thing to test.

**Comment by BlueViper85** [comment]
Tested in ZSNES 1.51 following your steps, chests, and items in your video from Sanctuary up through the chicken house and could not recreate.  Do you still have the SRM file for this at all?

**Comment by KatDevsGames** [comment]
Unable to reproduce in an emulator that isn't banned?

**Comment by BlueViper85** [comment]
I tried SNES9x 1.53 and ZSNES 1.51 and couldn't recreate in either situation with several attempts and methods.

**Comment by KatDevsGames** [comment]
Unable to reproduce. Closed/invalid.

**Comment by NagolStrache** [comment]
Sorry for not responding sooner, I was busy with other things and couldn't find time until after this was closed. Anyways, I wanted to give you guys the SRM file I had, maybe it'll work?

[C1852772 SRM.zip](https://github.com/Dessyreqt/alttprandomizer/files/440251/C1852772.SRM.zip)

**Comment by BlueViper85** [comment]
Confirmed that the provided SRM DOES in fact contain the issue for me.  Load up Save File 1, leave the house/cave (depending on where you load) and use the flute, fly to 3 and notice that the windmill is still intact showing that the flute was not manually activated.

Thanks for providing the SRM!

**Comment by BlueViper85** [comment]
Looking further into this, I loaded up the provided SRM and found that they also had the Powder available to select.  According to the spoiler log the Powder was on the mountain in the "Wall of Caves" area, in  the room with the crystal switch and five chests.

Since they had the active flute (without having activated the Weather Vane) my initial thought was maybe they had just obtained the powder with the active flute.  So I flew to the mountain myself and checked and found that the powder had NOT been naturally obtained.  Given that these are both switchable items in the menu, this suggests that this is not a coincidence.

The SRM included a second save named TEST, I attempted to recreate with that and was unable to.  I created a third save with the same name as was used on the first save slot (in case the name somehow caused an issue) and again could not recreate.  Tried a new SRM with the same name in slot 1 and could not recreate there either under basic testing.  Will do more later.

**Comment by NagolStrache** [comment]
I didn't even know that the powder was in the mountain, as I stopped playing and came to tell you guys after I encounter this for the first time. I wondered if my SRM file had anything to do with it, so I deleted it and after making my way back to the shovel found that I could still access the ocarina. Only thing other thing I can really think to add is that I always click PAL before loading the sfc file, but I don't think that has anything to do with this.

**Comment by KatDevsGames** [comment]
Why are you setting the game into PAL?

On September 2, 2016 6:57:01 PM EDT, NagolStrache notifications@github.com wrote:

> I didn't even know that the powder was in the mountain, as I stopped
> playing and came to tell you guys after I encounter this for the first
> time. I wondered if my SRM file had anything to do with it, so I
> deleted it and after making my way back to the shovel found that I
> could still access the ocarina. Only thing other thing I can really
> think to add is that I always click PAL before loading the sfc file,
> but I don't think that has anything to do with this.
> 
> ## 
> 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/93#issuecomment-244505897

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by BlueViper85** [comment]
I will test the PAL setting on my own computer later this evening to confirm the relation (unless someone else beats me to it)

**Comment by BlueViper85** [comment]
Loaded in ZSNES with PAL and tested a few scenarios and could not recreate confirming it's not related to PAL setting at least (not unexpectedly, but it was a quick enough thing worth testing).  Are you aware of any other settings you use or may have changed at all?

**Comment by KatDevsGames** [comment]
Why are we playing an NTSC game in PAL mode? 

On September 2, 2016 7:55:14 PM EDT, BlueViper85 notifications@github.com wrote:

> Loaded in ZSNES with PAL and tested a few scenarios and could not
> recreate confirming it's not related to PAL setting at least (not
> unexpectedly, but it was a quick enough thing worth testing).  Are you
> aware of any other settings you use or may have changed at all?
> 
> ## 
> 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/93#issuecomment-244512396

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by NagolStrache** [comment]
Honestly...Not really sure. Back on the first seed I played through in V5, I loaded up my rom to continue and experienced a weird graphical bug. I thought switching to PAL would somehow fix it (forgetting that Japan uses NTSC not Pal), and it worked so I just kept it that way ever since. I loaded up my rom in NTSC and it works fine, no weird borders on the title screen.

I just looked into the way I randomized the rom, and I think I found what was causing it. When I originally made this rom I also noticed Zarby89's application and was curious about what it did. I recreated the seed with the SRAM trace turned off and played all the way to the shovel. The option to switch to the ocarina with Y was not available, so I think that's what caused it.

I greatly apologize for making you guys look into something that didn't need to be. I don't know if SRAM is suppose to do that, but atleast we know what causes it.

**Comment by BlueViper85** [comment]
I'll have to try with those options on. I haven't tried with the trace or HUD active. I'd hate to jump to the conclusion that this is what caused it until it can be recreated. Otherwise the fact that it stopped working could also be a fluke. As much as it may seem obvious, being confident in the cause is important.

If that is found to be the cause then that's still something that can be investigated further, as the SRAM trace for that took was built so that the two applications can work together.

Thanks for your additional information. I'll follow up after I've tested with this active and see what happens.

**Comment by BlueViper85** [comment]
I completed more testing this afternoon.

I turned on SRAM Trace, and generated the ROM, opens the HUD tool and loaded up SNES9x and went to town (literally) and nothing special happened

So then I loaded up ZSNES and then loaded the same ROM (I did use PAL setting) and again went to the town as fast I could (going through escape and everything) and as soon as I picked up the mushroom I could switch to powder and as soon as I picked up the shovel I could switch to the activated flute.

I'm doing a little more testing to validate PAL v NTSC settings.  I'll edit this note when I'm done.

[EDIT] So I deleted my SRM and all save states and reloaded the game, this time forcing NTSC instead of PAL and noticed the same issue.  I then deleted the files again and loaded up the same ROM without forcing PAL or NTSC and had the same thing happened.  So this seems specific to having the SRAM Trace option enabled and using ZSNES 1.53 (regardless of whether the HUD is running or not))

**Comment by KatDevsGames** [comment]
I think I can fix this but just keep in mind that since ZSNES is banned 
by SRL anyway, it's going to be low priority.

**Comment by BlueViper85** [comment]
An updated report from ChristosOwen stating:

re: early flute from shovel bug report, also happened to komatsu, he played on snesgt v0.23 beta. If that's of any use to you in your investigation!

This emulator is more well-accepted than ZSNES and at least by some rules allowed for use with speed run submissions (I believe by ZSR rules).  While I expect that this may be caused by the same setting, I will test this tonight to confirm.

**Comment by KatDevsGames** [comment]
Did you get a chance to confirm this?

**Comment by BlueViper85** [comment]
I completely let this slip my mind, I apologize.  I just finished testing in the latest version of SNESTGT English v0218 and confirmed that the same thing happens in this emulator.  The Mushroom gives access to both the Powder and Mushroom and the Shovel gives access to both the Shovel and the activated Flute.

**Comment by ChristosOwen** [comment]
This had been addressed and will be working correctly in v7.
